default_config:
history:
wake_on_lan:
webhook:
my:
api:

logger:
  # default: CRITICAL
  # logs:
  #   custom_components.area_occupancy: debug

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24
    - 192.168.100.0/24
    - 192.168.200.0/24
    - 192.168.50.0/24
    - 172.30.33.0/24
    - 172.30.33.3
    - 127.0.0.1
    - ::1

homeassistant:
  packages: !include_dir_merge_named configuration/
  allowlist_external_dirs:
    - /config

automation: !include automations.yaml
script: !include scripts.yaml

