
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

speedtestdotnet:
system_health:
ffmpeg:
stream:
mobile_app:
wake_on_lan:
auto_backup:
calendar: !include calendars.yaml
cloud: !include cloud.yaml
script: !include scripts.yaml
camera: !include cameras.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
scene: !include scenes.yaml
zone: !include zones.yaml
automation: !include automations.yaml
media_player: !include media_player.yaml
device_tracker: !include device_tracker.yaml
notify: !include notify.yaml
switch: !include switches.yaml
shell_command: !include shell_command.yaml
homeassistant:
  customize: !include customize.yaml

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret
  
octopusagile:
  region_code: !secret octopus_region
  mpan: !secret octopus_mpan
  serial: !secret octopus_serial
  auth: !secret octopus_auth
  startdate: "2020-11-12"
  
panasonic_viera:
  host: !secret panasonic_tv
  name: Bedroom TV Panasonic
  turn_on_action:
    - service: media_player.turn_on
      target:
        entity_id: media_player.bedroom_fire_tv_adb