default_config:
history:
wake_on_lan:
webhook:
<<<<<<< HEAD
my:
=======
# zigbee2mqtt_networkmap:
>>>>>>> fcf4702d6d9777c62f997420e234fb70032d0604

# o365:
#   client_secret: !secret o365_personal_secret
#   client_id: !secret o365_personal_client_id

<<<<<<< HEAD
=======
# google:
#   client_id: !secret google_client_id
#   client_secret: !secret google_secret

spotify:
  client_id: !secret spotify_clientid
  client_secret: !secret spotify_secret

home_connect:
  client_id: !secret homeconnect_id
  client_secret: !secret homeconnect_secret
>>>>>>> fcf4702d6d9777c62f997420e234fb70032d0604

homeassistant:
  packages: !include_dir_merge_named configuration/
  customize: !include customize.yaml
<<<<<<< HEAD
  allowlist_external_dirs:
    - /config
=======
>>>>>>> fcf4702d6d9777c62f997420e234fb70032d0604

automation: !include automations.yaml
script: !include scripts.yaml

frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js
  themes: !include_dir_merge_named themes
