<<<<<<< HEAD
outside:
  # Thermostats
  #----------------------------------#
  climate:
  # Binary Sensors
  #----------------------------------#

  # Binary Sensors
  #----------------------------------#
  binary_sensor:
    # Bayesian
    #----------------------------------#
    - platform: bayesian
      name: Outside Occupied
      prior: 0.02
      device_class: occupancy
      probability_threshold: 0.7
      observations:

        - platform: "state"
          entity_id: binary_sensor.outside_motion
          prob_given_true: 0.5136220
          prob_given_false: 0.0002977
          to_state: "on"

  # Variable Sensors
  #----------------------------------#
  sensor:

  # Template Sensors
  #----------------------------------#
  template:
    # Template Binary Sensors
    #----------------------------------#
    binary_sensor:
      # Bright Sensors
      #----------------------------------#

    # Template Variable Sensors
    #----------------------------------#
    sensor:

  # Media Players
  #----------------------------------#
  media_player:

  # Notification Platforms
  #----------------------------------#
  notify:

  # Shell Commands
  #----------------------------------#
  shell_command:

  # Switches
  #----------------------------------#
  switch:
=======
outside:
  # Binary Sensors
  binary_sensor:
    ####################################
    # Trend Binary Sensors
    ####################################
    - platform: trend
      sensors:
        # Humidity
        area_outside_humidity_trend:
          friendly_name: Area - Outside Humidity Trend
          entity_id: sensor.area_outside_humidity
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.011
          device_class: moisture
        # Temperature
        area_outside_temperature_trend:
          friendly_name: Area - Outside Temperature Trend
          entity_id: sensor.area_outside_temperature
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.0017
          device_class: heat
  # Sensors
  sensor:

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:

  # Climate
  climate:

  # Media Player
  media_player:

  # Notify
  notify:

  # Shell Command
  shell_command:

  # Switches
  switch:
>>>>>>> fcf4702d6d9777c62f997420e234fb70032d0604
