outside:
  binary_sensor:
    - platform: bayesian
      name: Outside Occupied
      prior: 0.02
      device_class: occupancy
      probability_threshold: 0.7
      observations:

        - platform: "state"
          entity_id: binary_sensor.outside_motion
          prob_given_true: 0.5136220
          prob_given_false: 0.0002977
          to_state: "on"
