alias: Room - Kitchen - Lights
id: c7c321fd-d55a-46fe-8b1f-052f54371ec9
description: ""
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.area_kitchen_occupied
      - binary_sensor.area_kitchen_bright
      - input_boolean.area_kitchen_automations
      - binary_sensor.area_kitchen_humidity_trend
      - binary_sensor.area_kitchen_temperature_trend
      - binary_sensor.people_home

condition:
  - condition: state
    entity_id: input_boolean.area_kitchen_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            state: "on"
            entity_id: binary_sensor.area_kitchen_occupied
          - condition: state
            state: "off"
            entity_id: binary_sensor.area_kitchen_bright
          - condition: state
            state: "on"
            entity_id: binary_sensor.people_home
        sequence:
          - service: light.turn_on
            target:
              area_id: kitchen
            data:
              transition: 3
              color_temp: "{{ state_attr('switch.adaptive_lighting_adaptive_lights', 'color_temp_mired') }}"
              brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lights', 'brightness_pct') | int }}"
    default:
      - service: light.turn_off
        target:
          area_id: kitchen
        data:
          transition: 3
