# MQTT Connection, if empty will query and use hassio provided mqtt
mqtt:
  host:
  port: 1883
  ssl: false
  username:
  password:

# How long before device considered stale
timeout: 30
# How long before device is considered away
away_timeout: 120

# Floors w/ the points to draw it in meters
floors:
  - id: upstairs
    name: Upstairs
  # Bounds (x,y,z) of map in meters
    bounds: [[-1, -1, 2.5], [20, 8, 5]]
    rooms:
      - name: Study
        points:
          - [0, 0]
          - [0, 1.26]
          - [1, 1.26]
          - [1, 2.55]
          - [4.215, 2.55]
          - [4.215, 0]
      - name: Stairs
        points:
          - [0, 1.26]
          - [0, 4.71]
          - [1, 4.71]
          - [1, 1.26]
      - name: Hall
        points:
          - [1, 2.55]
          - [1, 4.71]
          - [2.27, 4.71]
          - [2.27, 2.55]
      - name: Bathroom
        points:
          - [2.27, 2.55]
          - [2.27, 4.71]
          - [4.215, 4.71]
          - [4.215, 2.55]
      - name: Bedroom
        points:
          - [0, 4.71]
          - [0, 7.73]
          - [4.215, 7.73]
          - [4.215, 4.71]
  - id: downstairs
    name: Downstairs
  # Bounds (x,y,z) of map in meters
    bounds: [[-1, -1, 0], [20, 8, 2.5]]
    rooms:
      - name: Utility Cupboard
        points:
          - [0, 0] # Bottom left
          - [0, 1.26] # Top left
          - [0.85, 1.26] # Top right
          - [0.85, 0] # Bottom right
      - name: Entrance
        points:
          - [0.85, 0] # Bottom left
          - [0.85, 1.26] # Top left
          - [2.58, 1.26] # Top right
          - [2.58, 0] # Bottom right
      - name: Toilet
        points:
          - [2.58, 0] # Bottom left
          - [2.58, 1.26] # Top left
          - [4.215, 1.26] # Top right
          - [4.215, 0] # Bottom right
      - name: Stairs
        points:
          - [0, 1.26] # Bottom left
          - [0, 4.13] # Top left
          - [1, 4.13] # Top right
          - [1, 1.26] # Bottom right
      - name: Kitchen
        points:
          - [1, 1.26] # Bottom left
          - [1, 4.13] # Top left
          - [4.215, 4.13] # Top right
          - [4.215, 1.26] # Bottom right
      - name: Lounge
        points:
          - [0, 4.13] # Bottom left
          - [0, 7.73] # Top left
          - [4.215, 7.73] # Top right
          - [4.215, 4.13] # Bottom right

# Locations of espresense nodes in meters
nodes:
  - name: bedroom-esp-1
    point: [4.1, 5.1, 0.2]
    floors: ["upstairs"]
  - name: bedroom-esp-2
    point: [0.8, 6.18, 1.75]
    floors: ["upstairs"]
  - name: study-esp-1
    point: [4.1, 0.4, 0.45]
    floors: ["upstairs"]
  - name: hall-esp-1
    point: [2.2, 4.55, 0.2]
    floors: ["upstairs"]
  - name: kitchen-esp-1
    point: [2.9, 1.6, 2]
    floors: ["downstairs"]
  - name: lounge-esp-1
    point: [3.8, 6.8, 0.2]
    floors: ["downstairs"]
  - name: lounge-esp-2
    point: [0.1, 4.7, 0.4]
    floors: ["downstairs"]
  - name: lounge-esp-3
    point: [1.2, 7.71, 0.4]
    floors: ["downstairs"]
  - name: entrance-esp-1
    point: [2.52, 0.15, 0.2]
    floors: ["downstairs"]
  - name: entrance-esp-2
    point: [0.8, 1.15, 0.2]
    floors: ["downstairs"]

# Devices to track
devices:
  - id: '*'
  - id: iBeacon:113b66e1-999d-4820-b246-62feffecf7e9-100-1
    name: Seb's Phone
  - id: iBeacon:29360bbc-24a3-415f-834a-d7ddcab4da74-100-1
    name: Laura's Phone
  - id: tile:e6f994abeb40
    name: Seb's Wallet
  - id: tile:c32f4c23248c
    name: Seb's Keys
  - id: tile:de2a2a7d78d7
    name: Laura's Keys
  - id: name:juul2-qujeah90
    name: Seb's Puffer 1
  - id: name:juul2-qmfypgct
    name: Seb's Puffer 2
  - id: iBeacon:75be550c-9bf4-4c6d-b503-329fcd3e041b-100-1
    name: Tablet
  - id: 'ad:0xfef3'
    name: Seb's Headphones
  - id: msft:cdp:0922
    name: Starrunner
  - id: iBeacon:123a6162-8154-4093-8d66-92c7de4a28ff-100-1
    name: Seb's Watch