<<<<<<< HEAD
toilet:
  # Binary Sensors
  #----------------------------------#
  binary_sensor:
    # Bayesian
    #----------------------------------#
    - platform: bayesian
      name: Toilet Occupied
      prior: 0.01
      device_class: occupancy
      probability_threshold: 0.19
      observations:

        - platform: "state"
          entity_id: binary_sensor.toilet_bright
          prob_given_true: 0.0119643
          prob_given_false: 0.0011671
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.toilet_motion
          prob_given_true: 0.2587902
          prob_given_false: 0.0001107
          to_state: "on"

        - platform: "state"
          entity_id: climate.toilet_radiator
          prob_given_true: 0.0714851
          prob_given_false: 0.0065530
          to_state: "heat"
  # Variable Sensors
  #----------------------------------#
  sensor:

  # Template Sensors
  #----------------------------------#
  template:
    # Template Binary Sensors
    #----------------------------------#
    binary_sensor:
      # Bright Sensors
      #----------------------------------#
      - unique_id: toilet_bright
        name: "Toilet Bright"
        device_class: light
        attributes:
          current_illuminance: "{{ (states('sensor.toilet_illuminance') | float(0)) }}"
          light_state: "{{ states('light.toilet') }}"
          sun: "{{ states('sun.sun') }}"
        state: |
          {% if states('sensor.toilet_illuminance') | int(0) > (states('input_number.toilet_illuminance_level') | int(0) * 1.3) and is_state('light.toilet', 'off') %}
            True
          {% elif states('sensor.toilet_illuminance') | int(0) > (states('input_number.toilet_illuminance_level') | int(0) * 3) %}
            True
          {% elif ((states('input_number.toilet_illuminance_level') | int(0) < states('sensor.toilet_illuminance') | int(0) < (states('input_number.toilet_illuminance_level') | int(0) * 1.3 ))) and (as_timestamp(now())-as_timestamp(states.binary_sensor.toilet_bright.last_changed) < 300) %}
            {{ states('binary_sensor.toilet_bright') }}
          {% elif states('sensor.toilet_illuminance') | int(0) < states('input_number.toilet_illuminance_level') | int(0) %}
            False
          {% else %}
            False
          {% endif %}

    # Template Variable Sensors
    #----------------------------------#
    sensor:
      # Probabilities
      #----------------------------------#
        
  # Media Players
  #----------------------------------#
  media_player:

  # Notification Platforms
  #----------------------------------#
  notify:

  # Shell Commands
  #----------------------------------#
  shell_command:

  # Switches
  #----------------------------------#
  switch:
=======
toilet:
  # Binary Sensors
  binary_sensor:
    - platform: bayesian
      name: Area - Toilet Occupied
      prior: 0.02
      device_class: occupancy
      probability_threshold: 0.6
      observations:
        - platform: "state"
          entity_id: "group.area_toilet_motion"
          prob_given_true: 0.48
          prob_given_false: 0.0043
          to_state: "on"
    ####################################
    # Trend Binary Sensors
    ####################################
    - platform: trend
      sensors:
        # Humidity
        area_toilet_humidity_trend:
          friendly_name: Area - Toilet Humidity Trend
          entity_id: sensor.area_toilet_humidity
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.011
          device_class: moisture
        # Temperature
        area_toilet_temperature_trend:
          friendly_name: Area - Toilet Temperature Trend
          entity_id: sensor.area_toilet_temperature
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.0017
          device_class: heat
  # Sensors
  sensor:
    - platform: min_max
      name: Area - Toilet Temperature
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.rad_04_temperature
    - platform: min_max
      name: Area - Toilet Illuminance
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.toilet_lux_06_illuminance_lux

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:
    area_toilet_motion:
      name: Area - Toilet Motion
      icon: mdi:motion-sensor
      entities:
        - binary_sensor.toilet_mot_07_occupancy
    area_toilet_windows:
      name: Area - Toilet Windows
      icon: mdi:window-closed
      entities:
        - binary_sensor.toilet_win_04_contact
  # Climate
  climate:
    - platform: climate_group
      name: Area - Toilet Climate
      temperature_unit: C
      entities:
        - climate.toilet_rad_04
        - climate.stairs_tst_01

  # Media Player
  media_player:

  # Notify
  notify:

  # Shell Command
  shell_command:

  # Switches
  switch:
>>>>>>> fcf4702d6d9777c62f997420e234fb70032d0604
