entrance:
  # Binary Sensors
  binary_sensor:
    - platform: bayesian
      name: Area - Entrance Occupied
      prior: 0.0208
      device_class: occupancy
      probability_threshold: 0.7
      observations:
        - platform: "state"
          entity_id: "binary_sensor.entrance_dor_03_contact"
          prob_given_true: 0.0960
          prob_given_false: 0.0001
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.zone_entrance_person_motion"
          prob_given_true: 0.9600
          prob_given_false: 0.0010
          to_state: "on"
        - platform: "state"
          entity_id: "group.area_entrance_motion"
          prob_given_true: 0.9600
          prob_given_false: 0.0020
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.front_door_motion"
          prob_given_true: 0.0480
          prob_given_false: 0.0007
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.area_entrance_bright"
          prob_given_true: 16.8
          prob_given_false: 0.3217
          to_state: "on"
    ####################################
    # Trend Binary Sensors
    ####################################
    - platform: trend
      sensors:
        # Humidity
        area_entrance_humidity_trend:
          friendly_name: Area - Entrance Humidity Trend
          entity_id: sensor.area_entrance_humidity
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.011
          device_class: moisture
        # Temperature
        area_entrance_temperature_trend:
          friendly_name: Area - Entrance Temperature Trend
          entity_id: sensor.area_entrance_temperature
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.0017
          device_class: heat
  # Sensors
  sensor:
    - platform: min_max
      name: Area - Entrance Temperature
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.tst_01_temperature
    - platform: min_max
      name: Area - Entrance Illuminance
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.entrance_tablet_light
        - sensor.entrance_lux_04_illuminance_lux

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:
    area_entrance_motion:
      name: Area - Entrance Motion
      icon: mdi:motion-sensor
      entities:
        - binary_sensor.zone_entrance_person_motion
    area_entrance_doors:
      name: Area - Entrance Doors
      icon: mdi:door
      entities:
        - binary_sensor.entrance_dor_03_contact
  # Climate
  climate:
    - platform: climate_group
      name: Area - Entrance Climate
      temperature_unit: C
      entities:
        - climate.stairs_tst_01

  # Media Player
  media_player:

  # Notify
  notify:

  # Shell Command
  shell_command:

  # Switches
  switch:
