substitutions:
  name: "bedside-speaker"
  friendly_name: Bedside Speaker

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  board: esp-wrover-kit
  framework:
    type: arduino

external_components:
  - source: github://pr#3552  # DAC support
    components: [es8388]
    refresh: 0s

logger:

api:

ota:
  platform: esphome
  password: !secret esp_ota

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

es8388:

i2c:
  - id: i2c_bus
    sda: GPIO18
    scl: GPIO23

i2s_audio:
  - id: i2s_audio_bus
    i2s_lrclk_pin: GPIO25
    i2s_bclk_pin: GPIO5
    i2s_mclk_pin: GPIO0

media_player:
  - platform: i2s_audio
    name: Media
    id: media
    dac_type: external
    i2s_audio_id: i2s_audio_bus
    i2s_dout_pin: GPIO26
    mode: mono
    mute_pin:
      number: GPIO21
      inverted: true

microphone:
  - platform: i2s_audio
    id: luxe_microphone
    i2s_audio_id: i2s_audio_bus
    i2s_din_pin: GPIO35
    adc_type: external
    pdm: false

light:
  - platform: fastled_clockless
    name: None
    id: top_led
    pin: GPIO22
    chipset: SK6812
    num_leds: 1
    rgb_order: grb
    gamma_correct: 2.8
    effects:
      - pulse:
          transition_length: 250ms
          update_interval: 250ms

button:
  - platform: restart
    name: Restart Device

  - platform: safe_mode
    name: Safe Mode Boot

  - platform: factory_reset
    name: Factory Reset

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO19
      inverted: true
      mode: INPUT_PULLUP
    name: Volume Up
    on_click:
      - media_player.volume_up: media
  - platform: gpio
    pin:
      number: GPIO32
      inverted: true
      mode: INPUT_PULLUP
    name: Volume Down
    on_click:
      - media_player.volume_down: media
  - platform: gpio
    pin:
      number: GPIO12
      inverted: true
      mode:
        input: true
        pullup: true
    name: Action
    id: action_button
    on_multi_click:
      - timing:
          - ON FOR AT MOST 350ms
          - OFF FOR AT LEAST 10ms
        then:
          - media_player.toggle: media