substitutions:
  name: raspiaudio-muse-luxe-6b49cc
  friendly_name: Bedside Speaker | Right
packages:
  raspiaudio.muse-luxe: github://esphome/media-players/raspiaudio/raspiaudio-muse-luxe.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: JYz6UZenDtWqw6ccZwkSjbf/l8YyMwdzFvZpqsXZCwA=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
