substitutions:
  name: hall-presence
packages:
  LoopOn.Unity: github://LoopOnCode/UnitySensor/esphome/loopon_unity.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: NHu7oTBERlOU88WtZASJpb3OSoxOwplTC8xO3h0BZnw=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
