####################################
# Statistics Sensors
####################################
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.downstairs_temp
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.study_temp
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.bathroom_temp
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.bedroom_temp
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.toilet_temp
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.bathroom_multisensor_temperature_air
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.bedroom_trisensor_temperature_air
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.hall_trisensor_temperature_air
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.kitchen_trisensor_temperature_air
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.lounge_trisensor_temperature_air
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.study_trisensor_temperature_air
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.toilet_trisensor_temperature_air
####################################
# Lux Averages
####################################
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.study_trisensor_illuminance
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.bedroom_trisensor_illuminance
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.hall_trisensor_illuminance
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.bathroom_multisensor_illuminance
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.lounge_trisensor_illuminance
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.kitchen_trisensor_illuminance
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.toilet_trisensor_illuminance

####################################
# Humidity Averages
####################################
- platform: statistics
  max_age:
    hours: 24
  entity_id: sensor.bathroom_multisensor_humidity_air

####################################
# Ratios
####################################
- platform: history_stats
  name: Ratio PC Active
  entity_id: binary_sensor.seb_pc_active
  state: "on"
  type: ratio
  start: "{{ now() - timedelta(days=7) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Ratio Study Motion
  entity_id: binary_sensor.study_trisensor_motion
  state: "on"
  type: ratio
  start: "{{ now() - timedelta(days=7) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Ratio Seb Study Presence
  entity_id: sensor.seb_phone_ble_room_presence
  state: "Study"
  type: ratio
  start: "{{ now() - timedelta(days=7) }}"
  end: "{{ now() }}"
