####################################
# Statistics Sensors
####################################
- platform: average
  name: "Home Temperature"
  entities:
    - sensor.downstairs_temp
    - sensor.study_temp
    - sensor.bathroom_temp
    - sensor.bedroom_temp
    - sensor.toilet_temp
    - sensor.bathroom_multisensor_temperature_air
    - sensor.bedroom_trisensor_temperature_air
    - sensor.hall_trisensor_temperature_air
    - sensor.kitchen_trisensor_temperature_air
    - sensor.lounge_trisensor_temperature_air
    - sensor.study_trisensor_temperature_air
    - sensor.toilet_trisensor_temperature_air
####################################
# Lux Averages
####################################
- platform: average
  name: "Study Average Lux"
  precision: 0
  duration:
    days: 1
  entities:
    - sensor.study_trisensor_illuminance
- platform: average
  name: "Bedroom Average Lux"
  precision: 0
  duration:
    days: 1
  entities:
    - sensor.bedroom_trisensor_illuminance
- platform: average
  name: "Hall Average Lux"
  precision: 0
  duration:
    days: 1
  entities:
    - sensor.hall_trisensor_illuminance
- platform: average
  name: "Bathroom Average Lux"
  precision: 0
  duration:
    days: 1
  entities:
    - sensor.bathroom_multisensor_illuminance
- platform: average
  name: "Lounge Average Lux"
  precision: 0
  duration:
    days: 1
  entities:
    - sensor.lounge_trisensor_illuminance
- platform: average
  name: "Kitchen Average Lux"
  precision: 0
  duration:
    days: 1
  entities:
    - sensor.kitchen_trisensor_illuminance
- platform: average
  name: "Toilet Average Lux"
  precision: 0
  duration:
    days: 1
  entities:
    - sensor.toilet_trisensor_illuminance

####################################
# Humidity Averages
####################################
- platform: average
  name: "Bathroom Average Humidity"
  precision: 0
  duration:
    hours: 4
  entities:
    - sensor.bathroom_multisensor_humidity_air

- platform: history_stats
  name: Ratio PC Active
  entity_id: binary_sensor.seb_pc_active
  state: "on"
  type: ratio
  start: "{{ now() - timedelta(days=7) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Ratio Study Motion
  entity_id: binary_sensor.study_trisensor_motion
  state: "on"
  type: ratio
  start: "{{ now() - timedelta(days=7) }}"
  end: "{{ now() }}"
- platform: history_stats
  name: Ratio Seb Study Presence
  entity_id: sensor.seb_phone_ble_room_presence
  state: "Study"
  type: ratio
  start: "{{ now() - timedelta(days=7) }}"
  end: "{{ now() }}"