ptz:
  name: PTZ
  description: Pan and tilt camera
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    tilt:
      description: "Tilt direction."
      example: "UP"
      name: Tilt
      selector:
        select:
          options:
            - "UP"
            - "DOWN"
    pan:
      name: Pan
      description: "Pan direction."
      example: "RIGHT"
      selector:
        select:
          options:
            - "RIGHT"
            - "LEFT"
    preset:
      name: Preset
      description: "PTZ preset ID or a Name. See possible presets in entity attributes"
      example: "1"
      selector:
        text:
    distance:
      name: Distance
      description: "Sets how much PTZ should be executed in one request."
      example: "0.1"
      selector:
        number:
          min: 0
          max: 1
          step: 0.01
          unit_of_measurement: "%"
          mode: slider
set_day_night_mode:
  name: Set day / night mode
  description: Sets day or night mode
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    day_night_mode:
      required: true
      name: Mode
      description: "Sets day / night mode for camera."
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
            - "auto"
set_privacy_mode:
  name: Set privacy mode
  description: Sets privacy mode
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    privacy_mode:
      name: Mode
      required: true
      description: "Sets privacy mode for camera."
      selector:
        select:
          options:
            - "on"
            - "off"
set_alarm_mode:
  name: Set alarm mode
  description: Sets alarm mode
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    alarm_mode:
      name: Mode
      description: "Sets alarm mode for camera."
      example: "on"
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"
    sound:
      name: Sound
      description: "Sets whether the alarm should use sound on motion detected."
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
    light:
      name: Light
      description: "Sets whether the alarm should use light on motion detected."
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
set_led_mode:
  name: Set LED mode
  description: Sets LED mode
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    led_mode:
      name: Mode
      required: true
      description: "Sets LED mode for camera."
      example: "on"
      selector:
        select:
          options:
            - "on"
            - "off"
set_motion_detection_mode:
  name: Set motion detection mode
  description: Sets motion detection mode
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    motion_detection_mode:
      required: true
      name: Mode
      description: "Sets motion detection mode for camera."
      example: "normal"
      selector:
        select:
          options:
            - "high"
            - "normal"
            - "low"
            - "off"
set_auto_track_mode:
  name: Set auto track mode
  target:
    entity:
      domain: camera
      integration: tapo_control
  description: >
    Sets auto track mode. 

    WARNING: This mode is not available in Tapo app and we do not know why. Use at your own risk and please report any success or failures in GitHub.
  fields:
    auto_track_mode:
      description: "Sets auto track mode for camera."
      example: "on"
      name: Mode
      required: true
      selector:
        select:
          options:
            - "on"
            - "off"
reboot:
  name: Reboot
  description: Reboots the camera
  target:
    entity:
      domain: camera
      integration: tapo_control
save_preset:
  name: Save preset
  description: Saves the current PTZ position to a preset
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    name:
      description: "Name of the preset."
      example: "Entry Door"
      required: true
      name: Name
      selector:
        text:
delete_preset:
  name: Delete preset
  description: Deletes a preset
  target:
    entity:
      domain: camera
      integration: tapo_control
  fields:
    preset:
      description: "PTZ preset ID or a Name. See possible presets in entity attributes"
      example: "1"
      required: true
      name: Name
      selector:
        text:
format:
  name: Format
  description: Formats the SD card of a camera
  target:
    entity:
      domain: camera
      integration: tapo_control
