alias: Room - Hall - Lights
id: d0cccb19-ad9a-407e-9e5b-e5bb81f23cc9
description: ""
mode: queued

trigger:
  - platform: state
    entity_id:
      - binary_sensor.area_hall_occupied

condition:
  - condition: state
    entity_id: input_boolean.area_hall_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.area_hall_occupied
            state: "on"
          - condition: state
            entity_id: input_boolean.sleep_mode
            state: "off"
          - condition: state
            entity_id: sun.sun
            state: below_horizon
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 6
            target:
              entity_id: light.hall_lights
      - conditions:
          - condition: state
            entity_id: binary_sensor.area_hall_occupied
            state: "on"
          - condition: state
            entity_id: input_boolean.sleep_mode
            state: "on"
          - condition: state
            entity_id: sun.sun
            state: below_horizon
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 1
            target:
              entity_id: light.hall_lights
    default:
      - service: light.turn_off
        target:
          entity_id: light.hall_lights
