home:
  binary_sensor:
    - platform: bayesian
      name: Home Occupied
      prior: 0.52
      device_class: occupancy
      probability_threshold: 0.7
      observations:
        - platform: "state"
          entity_id: binary_sensor.home_motion
          prob_given_true: 0.6031935
          prob_given_false: 0.0135159
          to_state: "on"

  sensor:
  template:
    binary_sensor:
      - unique_id: people_home
        name: "People Home"
        icon: "mdi:home"
        device_class: occupancy
        state: |
          {{ is_state_attr('sensor.laura_location', 'Location', 'Home') or is_state_attr('sensor.seb_location', 'Location', 'Home') or is_state('device_tracker.laura_phone_wifi', 'Home') or is_state('device_tracker.seb_phone_wifi', 'Home') or is_state('input_boolean.guest_mode', 'on') }}
