alias: Room - Entrance - Lights
id: f26a8757-9178-4334-b2dc-07fda3f01c30
description: ""
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - entity_id: binary_sensor.dor_03_contact
    platform: state
    to: "on"
  - entity_id: binary_sensor.dor_03_contact
    for: 00:00:30
    platform: state
    to: "off"
  - platform: state
    entity_id:
      - binary_sensor.area_entrance_occupied
      - binary_sensor.area_entrance_bright
      - input_boolean.area_entrance_automations
      - binary_sensor.people_home

condition:
  - condition: state
    entity_id: input_boolean.area_entrance_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: or
            conditions:
              - condition: and
                conditions:
                  - condition: state
                    state: "on"
                    entity_id: binary_sensor.area_entrance_occupied
                  - condition: state
                    state: "on"
                    entity_id: binary_sensor.people_home
              - condition: state
                state: "on"
                entity_id: binary_sensor.dor_03_contact
          - condition: state
            state: "off"
            entity_id: binary_sensor.area_entrance_bright
        sequence:
          - service: light.turn_on
            target:
              area_id: entrance
            data:
              transition: 3
              brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lights', 'brightness_pct') | int }}"
    default:
      - service: light.turn_off
        target:
          area_id: entrance
        data:
          transition: 3
