alias: Room - Entrance - Lights
id: f26a8757-9178-4334-b2dc-07fda3f01c30
description: ""
mode: queued

trigger:
  - entity_id: binary_sensor.dor_03_contact
    platform: state
    to: "on"
  - entity_id: binary_sensor.dor_03_contact
    for: 00:00:30
    platform: state
    to: "off"

condition:
  - condition: state
    entity_id: input_boolean.area_entrance_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.dor_03_contact
            state: "on"
          - condition: state
            entity_id: sun.sun
            state: below_horizon
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
            target:
              entity_id: light.entrance_lights
    default:
      - service: light.turn_off
        target:
          entity_id: light.entrance_lights
