lounge:
  # Binary Sensors
  #----------------------------------#
  binary_sensor:
    # Bayesian
    #----------------------------------#
    - platform: bayesian
      name: Lounge Occupied
      prior: 0.40
      device_class: occupancy
      probability_threshold: 0.7
      observations:

        - platform: "state"
          entity_id: binary_sensor.back_door_left_contact
          prob_given_true: 0.0028274
          prob_given_false: 0.0000972
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.back_door_right_contact
          prob_given_true: 0.1951905
          prob_given_false: 0.1543939
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.lounge_bright
          prob_given_true: 0.0474970
          prob_given_false: 0.2667856
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.lounge_doors
          prob_given_true: 0.1964286
          prob_given_false: 0.1551342
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.lounge_person_occupancy
          prob_given_true: 0.05
          prob_given_false: 0.0085813
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.lounge_motion
          prob_given_true: 0.3738080
          prob_given_false: 0.0080722
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.lounge_motion_1_occupancy
          prob_given_true: 0.3721682
          prob_given_false: 0.0080578
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.lounge_temperature_motion_lux_1_occupancy
          prob_given_true: 0.2849435
          prob_given_false: 0.0070264
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.lounge_tv_state
          prob_given_true: 0.3392574
          prob_given_false: 0.0077303
          to_state: "on"

        - platform: "state"
          entity_id: input_boolean.lounge_schedule
          prob_given_true: 0.1172500
          prob_given_false: 0.2712675
          to_state: "on"

        - platform: "state"
          entity_id: media_player.lounge_tv
          prob_given_true: 0.0661607
          prob_given_false: 0.0021306
          to_state: "playing"

  # Variable Sensors
  #----------------------------------#
  sensor:
  # Template Sensors
  #----------------------------------#
  template:
    # Template Binary Sensors
    #----------------------------------#
    binary_sensor:
      # Bright Sensors
      #----------------------------------#
      - unique_id: lounge_bright
        name: "Lounge Bright"
        device_class: light
        state: |
          {% set lux = states('sensor.lounge_illuminance') %}
          {% set threshold = states('input_number.lounge_illuminance_level') %}
          {% set selfState = states('binary_sensor.lounge_bright') %}
          {% set lightState = states('light.bedroom') %}
          {% set selfLastChanged = states.binary_sensor.lounge_bright.last_changed %}
          {% if threshold | int(0) == 0 %}
            False
          {% elif lux | int(0) > (threshold | int(0) * 1.3) and lightState == 'off' %}
            True
          {% elif lux | int(0) > (threshold | int(0) * 3) %}
            True
          {% elif ((threshold | int(0) < lux | int(0) < (threshold | int(0) * 1.3 ))) and (as_timestamp(now())-as_timestamp(selfLastChanged) < 300) %}
            {{ selfState }}
          {% elif lux | int(0) < threshold | int(0) %}
            False
          {% else %}
            False
          {% endif %}

    # Template Variable Sensors
    #----------------------------------#
    sensor:
      # Probabilities
      #----------------------------------#
      - unique_id: lounge_occupied_probability
        name: Lounge Occupied Probability
        state_class: measurement
        unit_of_measurement: "%"
        state: "{{ (state_attr('binary_sensor.lounge_occupied','probability')*100 | int(0) ) | round(0) }}"

  # Media Players
  #----------------------------------#
  media_player:
    - platform: wiim_custom
      host: 192.168.1.250
      name: Lounge Speakers Wiim
      uuid: 'FF98F09CAA6BA405CDE17CF2'

    - platform: universal
      name: Lounge Speakers
      browse_media_entity: media_player.lounge_speakers_wiim
      device_class: speaker
      unique_id: lounge_speakers
      children:
        - media_player.lounge_speakers_wiim
        - media_player.lounge_speakers_cast
        - media_player.lounge_speakers_alexa
        - media_player.lounge_speakers_dlna
        - media_player.lounge_speakers_ma
      commands:
        turn_on:
          service: media_player.turn_on
          target:
            entity_id: media_player.lounge_speakers_cast
        turn_off:
          service: media_player.media_stop
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_up:
          service: media_player.volume_up
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_down:
          service: media_player.volume_down
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_mute:
          service: media_player.volume_mute
          target:
            entity_id: media_player.lounge_speakers_wiim
        select_source:
          service: media_player.select_source
          target:
            entity_id: media_player.lounge_speakers_wiim
          data:
            source: "{{ source }}"
        volume_set:
          service: media_player.volume_set
          target:
            entity_id: media_player.lounge_speakers_wiim
          data:
            volume_level: "{{ volume_level }}"
      attributes:
        source: media_player.lounge_speakers_wiim|source
        source_list: media_player.lounge_speakers_wiim|source_list
        entity_picture: media_player.lounge_speakers_wiim|entity_picture
        media_album_name: media_player.lounge_speakers_wiim|media_album_name
        media_title: media_player.lounge_speakers_wiim|media_title
        media_duration: media_player.lounge_speakers_wiim|media_duration
        media_position: media_player.lounge_speakers_wiim|media_position

    - platform: universal
      name: Lounge TV
      browse_media_entity: media_player.lounge_tv_shield
      device_class: tv
      unique_id: lounge_tv
      children:
        - media_player.lounge_tv_adb
        - media_player.lounge_tv_cast
        - media_player.lounge_tv_dlna
        - media_player.lounge_tv_shield
        - media_player.lounge_tv_shield_cast
        - media_player.lounge_tv_sony
      commands:
        turn_on:
          service: media_player.turn_on
          target:
            entity_id: media_player.lounge_tv_shield
        turn_off:
          service: media_player.media_stop
          target:
            entity_id: media_player.lounge_tv_shield
        volume_up:
          service: media_player.volume_up
          target:
            entity_id: media_player.lounge_tv_shield
        volume_down:
          service: media_player.volume_down
          target:
            entity_id: media_player.lounge_tv_shield
        volume_mute:
          service: media_player.volume_mute
          target:
            entity_id: media_player.lounge_tv_shield
        select_source:
          service: media_player.select_source
          target:
            entity_id: media_player.lounge_tv_shield
          data:
            source: "{{ source }}"
        volume_set:
          service: media_player.volume_set
          target:
            entity_id: media_player.lounge_tv_shield
          data:
            volume_level: "{{ volume_level }}"
      attributes:
        source: media_player.lounge_tv_shield|source
        source_list: media_player.lounge_tv_shield|source_list
        entity_picture: media_player.lounge_tv_shield|entity_picture
        media_album_name: media_player.lounge_tv_shield|media_album_name
        media_title: media_player.lounge_tv_shield|media_title
        media_duration: media_player.lounge_tv_shield|media_duration
        media_position: media_player.lounge_tv_shield|media_position
  # Notification Platforms
  #----------------------------------#
  notify:

  # Shell Commands
  #----------------------------------#
  shell_command:
    # lounge_camera_turn_off: !secret loungecam_turn_off
    # lounge_camera_turn_on: !secret loungecam_turn_on
    # lounge_camera_floor: !secret loungecam_floor

  # Switches
  #----------------------------------#
  switch:

  command_line:
    # - switch:
    #     unique_id: lounge_camera_ir
    #     name: Lounge Camera Night Mode
    #     command_on: !secret loungecam_ir_on
    #     command_off: !secret loungecam_ir_off
    #     command_state: !secret loungecam_ir_state
    #     value_template: '{{ value == "1" }}'
    # - switch:
    #     unique_id: lounge_camera_motion
    #     name: Lounge Camera Motion Detection
    #     command_on: !secret loungecam_motion_on
    #     command_off: !secret loungecam_motion_off
    #     command_state: !secret loungecam_motion_state
    #     value_template: '{{ value == "1" }}'

  # Cameras
  #----------------------------------#
  camera:
