lounge:
  template:
    - binary_sensor:
        - name: Lounge Occupancy
          unique_id: lounge_occupancy
          device_class: occupancy
          state: |-
            {% set scores = namespace(total=0) %}
            {% if is_state('binary_sensor.lounge_motion', 'on') %}  {% set scores.total = scores.total + 3 %}{% endif %}
            {% if is_state('binary_sensor.lounge_doors', 'off') %}  {% set scores.total = scores.total + 3 %}{% endif %}
            {% if is_state('binary_sensor.lounge_tv_active', 'on') %}  {% set scores.total = scores.total + 3 %}{% endif %}
            {% if is_state('input_boolean.lounge_occupied_override', 'on') %}  {% set scores.total = scores.total + 5 %}{% endif %}
            {{ scores.total >= 3 }}
          attributes:
            confidence_score: |-
              {% set scores = namespace(total=0) %}
              {% if is_state('binary_sensor.lounge_motion', 'on') %}  {% set scores.total = scores.total + 3 %}{% endif %}
              {% if is_state('binary_sensor.lounge_doors', 'off') %}  {% set scores.total = scores.total + 3 %}{% endif %}
              {% if is_state('binary_sensor.lounge_tv_active', 'on') %}  {% set scores.total = scores.total + 3 %}{% endif %}
              {% if is_state('input_boolean.lounge_occupied_override', 'on') %}  {% set scores.total = scores.total + 5 %}{% endif %}
              {{ scores.total }}
            active_triggers: |-
              {% set triggers = [] %}
              {% if is_state('binary_sensor.lounge_motion', 'on') %}  {% set triggers = triggers + ['Motion Detected'] %}{% endif %}
              {% if is_state('binary_sensor.lounge_doors', 'off') %}  {% set triggers = triggers + ['Door Closed'] %}{% endif %}
              {% if is_state('binary_sensor.lounge_tv_active', 'on') %}  {% set triggers = triggers + ['TV Active'] %}{% endif %}
              {% if is_state('input_boolean.lounge_occupied_override', 'on') %}  {% set triggers = triggers + ['Manual Override'] %}{% endif %}
              {{ triggers|join(', ') }}
    - binary_sensor:
        - name: Lounge TV Active
          unique_id: lounge_tv_active
          state: |-
            {% set power = states('sensor.tv_power')|float(0) %}
            {{ power > 10 }}
          attributes:
            power_draw: >-
              {{ states('sensor.tv_power')|float(0) }}
            current_channel: >-
              {{ states('sensor.tv_channel') }}
            volume: >-
              {{ states('sensor.tv_volume')|int(0) }}
      sensor:
        - name: Lounge TV Status
          unique_id: lounge_tv_status
          state: >-
            {{ states('sensor.tv_state') }}
          attributes:
            input_source: >-
              {{ states('sensor.tv_input_source') }}
            hdmi_connected: >-
              {{ state_attr('sensor.tv_hdmi', 'connected_devices')|default([]) }}
        - name: Lounge TV Power State
          unique_id: lounge_tv_power_state
          state: |-
            {% set power = states('sensor.tv_power')|float(0) %}
            {% if power > 50 %}on{% elif power > 10 %}standby{% else %}off{% endif %}
    - sensor:
        - name: Total Power
          unique_id: total_power
          state: |-
            {% set components = [
                'sensor.lounge_tv_power',
                'sensor.lounge_entertainment_power'
            ] %}

            {% set total = namespace(power=0) %}
            {% for component in components %}
              {% set total.power = total.power + states(component)|float(0) %}
            {% endfor %}
            {{ total.power|round(2) }}
          attributes:
            tv: >-
              {{ states('sensor.lounge_tv_power')|float(0)|round(2) }}
            entertainment: >-
              {{ states('sensor.lounge_entertainment_power')|float(0)|round(2) }}
    - sensor:
        - name: Daily Energy
          unique_id: daily_energy
          state: |-
            {% set components = [
                'sensor.lounge_tv_daily_energy',
                'sensor.lounge_entertainment_daily_energy'
            ] %}

            {% set total = namespace(energy=0) %}
            {% for component in components %}
              {% set total.energy = total.energy + states(component)|float(0) %}
            {% endfor %}
            {{ total.energy|round(3) }}
          attributes:
            last_reset: >-
              {{ now().replace(hour=0, minute=0, second=0, microsecond=0).isoformat() }}
    - binary_sensor:
        - name: Lounge Temperature Rising
          unique_id: lounge_temp_rising
          state: |-
            {% set current = states('sensor.lounge_temperature')|float(20) %}
            {% set previous = state_attr('sensor.lounge_temperature', 'previous_value')|float(20) %}
            {% set threshold = 0.2 %}
            {{ (current - previous) > threshold }}
        - name: Lounge Temperature Falling
          unique_id: lounge_temp_falling
          state: |-
            {% set current = states('sensor.lounge_temperature')|float(20) %}
            {% set previous = state_attr('sensor.lounge_temperature', 'previous_value')|float(20) %}
            {% set threshold = 0.2 %}
            {{ (current - previous) < threshold }}
      sensor:
        - name: Lounge Temperature Differential
          unique_id: lounge_temp_differential
          state: |-
            {% set current = states('sensor.lounge_temperature')|float(20) %}
            {% set target = state_attr('climate.lounge', 'temperature')|float(20) %}
            {{ (current - target)|round(1) }}
          attributes:
            current_temp: >-
              {{ states('sensor.lounge_temperature')|float(20) }}
            target_temp: >-
              {{ state_attr('climate.lounge', 'temperature')|float(20) }}
            mode: >-
              {{ state_attr('climate.lounge', 'hvac_action')|default('off') }}
    - binary_sensor:
        - name: Lounge High Humidity
          unique_id: lounge_high_humidity
          state: |-
            {% set current = states('sensor.lounge_humidity')|float(50) %}
            {{ current > 75 }}
      sensor:
        - name: Lounge Humidity Change
          unique_id: lounge_humidity_change
          state: |-
            {% set current = states('sensor.lounge_humidity')|float(50) %}
            {% set average = states('sensor.sensor.lounge_humidity_average')|float(50) %}
            {{ ((current - average) / average * 100)|round(1) }}
          attributes:
            current_humidity: >-
              {{ states('sensor.lounge_humidity')|float(50) }}
            average_humidity: >-
              {{ states('sensor.sensor.lounge_humidity_average')|float(50) }}
  input_number:
    lounge_power_threshold:
      name: Lounge Power Alert Threshold
      min: 100.0
      max: 1000.0
      step: 50.0
      unit_of_measurement: W
      icon: mdi:flash-alert
      initial: 400.0
    lounge_temp_threshold:
      name: Lounge Temperature Threshold
      min: 19.0
      max: 25.0
      step: 0.5
      unit_of_measurement: °C
      icon: mdi:thermometer
      initial: 23.0
    lounge_light_brightness:
      name: Lounge Light Brightness
      min: 0.0
      max: 100.0
      step: 5.0
      unit_of_measurement: '%'
      icon: mdi:brightness-6
      initial: 100.0
    lounge_light_transition:
      name: Lounge Light Transition Time
      min: 0.0
      max: 10.0
      step: 0.5
      unit_of_measurement: s
      icon: mdi:transition
      initial: 5.0
    lounge_humidity_threshold:
      name: Lounge Humidity Threshold
      min: 30.0
      max: 80.0
      step: 1.0
      unit_of_measurement: '%'
      icon: mdi:water-percent
      initial: 60.0
  input_boolean:
    lounge_light_color_mode:
      name: Lounge Light Color Mode
      icon: mdi:palette
    lounge_tv_power_management:
      name: Lounge TV Power Management
      icon: mdi:television
    lounge_occupied_override:
      name: Lounge Manual Occupancy Override
      icon: mdi:account-check
    lounge_sleep_mode:
      name: Lounge Sleep Mode
      icon: mdi:power-sleep
    lounge_automations:
      name: Lounge Automations
      icon: mdi:robot

  media_player:
    - platform: wiim_custom
      host: 192.168.1.250
      name: Lounge Speakers Wiim
      uuid: 'FF98F09CAA6BA405CDE17CF2'

    - platform: universal
      name: Lounge Speakers
      browse_media_entity: media_player.lounge_speakers_wiim
      device_class: speaker
      unique_id: lounge_speakers
      children:
        - media_player.lounge_speakers_wiim
        - media_player.lounge_speakers_cast
        - media_player.lounge_speakers_alexa
        - media_player.lounge_speakers_dlna
        - media_player.lounge_speakers_ma
      commands:
        turn_on:
          service: media_player.turn_on
          target:
            entity_id: media_player.lounge_speakers_cast
        turn_off:
          service: media_player.media_stop
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_up:
          service: media_player.volume_up
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_down:
          service: media_player.volume_down
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_mute:
          service: media_player.volume_mute
          target:
            entity_id: media_player.lounge_speakers_wiim
        select_source:
          service: media_player.select_source
          target:
            entity_id: media_player.lounge_speakers_wiim
          data:
            source: "{{ source }}"
        volume_set:
          service: media_player.volume_set
          target:
            entity_id: media_player.lounge_speakers_wiim
          data:
            volume_level: "{{ volume_level }}"
      attributes:
        source: media_player.lounge_speakers_wiim|source
        source_list: media_player.lounge_speakers_wiim|source_list
        entity_picture: media_player.lounge_speakers_wiim|entity_picture
        media_album_name: media_player.lounge_speakers_wiim|media_album_name
        media_title: media_player.lounge_speakers_wiim|media_title
        media_duration: media_player.lounge_speakers_wiim|media_duration
        media_position: media_player.lounge_speakers_wiim|media_position

    - platform: universal
      name: Lounge TV
      browse_media_entity: media_player.lounge_tv_shield
      device_class: tv
      unique_id: lounge_tv
      children:
        - media_player.lounge_tv_adb
        - media_player.lounge_tv_cast
        - media_player.lounge_tv_dlna
        - media_player.lounge_tv_shield
        - media_player.lounge_tv_shield_cast
        - media_player.lounge_tv_sony
      commands:
        turn_on:
          service: media_player.turn_on
          target:
            entity_id: media_player.lounge_tv_shield
        turn_off:
          service: media_player.media_stop
          target:
            entity_id: media_player.lounge_tv_shield
        volume_up:
          service: media_player.volume_up
          target:
            entity_id: media_player.lounge_tv_shield
        volume_down:
          service: media_player.volume_down
          target:
            entity_id: media_player.lounge_tv_shield
        volume_mute:
          service: media_player.volume_mute
          target:
            entity_id: media_player.lounge_tv_shield
        select_source:
          service: media_player.select_source
          target:
            entity_id: media_player.lounge_tv_shield
          data:
            source: "{{ source }}"
        volume_set:
          service: media_player.volume_set
          target:
            entity_id: media_player.lounge_tv_shield
          data:
            volume_level: "{{ volume_level }}"
      attributes:
        source: media_player.lounge_tv_shield|source
        source_list: media_player.lounge_tv_shield|source_list
        entity_picture: media_player.lounge_tv_shield|entity_picture
        media_album_name: media_player.lounge_tv_shield|media_album_name
        media_title: media_player.lounge_tv_shield|media_title
        media_duration: media_player.lounge_tv_shield|media_duration
        media_position: media_player.lounge_tv_shield|media_position
