lounge:
  # Binary Sensors
  binary_sensor:
    - platform: bayesian
      name: Area - Lounge Occupied
      prior: 0.29
      device_class: occupancy
      probability_threshold: 0.8
      observations:
        - platform: "state"
          entity_id: "group.area_lounge_motion"
          prob_given_true: 0.25
          prob_given_false: 0.0176
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.zone_lounge_person_motion"
          prob_given_true: 0.59
          prob_given_false: 0.0294
          to_state: "on"
        - platform: "state"
          entity_id: "media_player.lounge_tv"
          prob_given_true: 0.3189
          prob_given_false: 0.0394
          to_state: "playing"
    ####################################
    # Trend Binary Sensors
    ####################################
    - platform: trend
      sensors:
        # Humidity
        area_lounge_humidity_trend:
          friendly_name: Area - Lounge Humidity Trend
          entity_id: sensor.area_lounge_humidity
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.011
          device_class: moisture
        # Temperature
        area_lounge_temperature_trend:
          friendly_name: Area - Lounge Temperature Trend
          entity_id: sensor.area_lounge_temperature
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.0017
          device_class: heat
  # Sensors
  sensor:
    - platform: min_max
      name: Area - Lounge Temperature
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.tst_01_temperature
    - platform: min_max
      name: Area - Lounge Illuminance
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.lounge_lux_08_illuminance_lux

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:
    area_lounge_motion:
      name: Area - Lounge Motion
      icon: mdi:motion-sensor
      entities:
        - binary_sensor.lounge_mot_02_occupancy
        - binary_sensor.lounge_mot_03_occupancy
    area_lounge_doors:
      name: Area - Lounge Doors
      icon: mdi:door
      entities:
        - binary_sensor.lounge_dor_01_contact
        - binary_sensor.lounge_dor_02_contact
  # Climate
  climate:
    - platform: climate_group
      name: Area - Lounge Climate
      temperature_unit: C
      entities:
        - climate.stairs_tst_01

  # Media Player
  media_player:
    - platform: androidtv
      device_class: firetv
      name: Lounge Fire TV ADB
      host: !secret lounge_fire_tv
    - platform: androidtv
      device_class: androidtv
      name: Lounge TV ADB
      host: !secret lounge_tv
      exclude_unnamed_apps: true
      apps:
        com.sony.dtv.hbbtvlauncher: "All 4"
        com.sony.dtv.tvx: "External Source"
    - platform: universal
      name: Lounge TV
      children:
        - media_player.lounge_fire_tv_adb
        - media_player.lounge_tv_adb
      commands:
        turn_on:
          service: media_player.turn_on
          data:
            entity_id: media_player.lounge_tv_adb
        turn_off:
          service: media_player.turn_off
          data:
            entity_id: media_player.lounge_tv_adb
        volume_up:
          service: media_player.volume_up
          data:
            entity_id: media_player.lounge_tv_adb
        volume_down:
          service: media_player.volume_down
          data:
            entity_id: media_player.lounge_tv_adb
        volume_mute:
          service: media_player.volume_mute
          data:
            entity_id: media_player.lounge_tv_adb
        select_source:
          service: media_player.select_source
          data:
            entity_id: media_player.lounge_fire_tv_adb
            source: "{{ source }}"
        volume_set:
          service: media_player.volume_set
          data:
            entity_id: media_player.lounge_tv_adb
            volume_level: "{{ volume_level }}"
      attributes:
        state: media_player.lounge_fire_tv
        is_volume_muted: media_player.lounge_tv_adb|is_volume_muted
        source: media_player.lounge_fire_tv_adb|source
        source_list: media_player.lounge_fire_tv_adb|source_list
  # Notify
  notify:

  # Shell Command
  shell_command:
    lounge_camera_turn_off: !secret loungecam_turn_off
    lounge_camera_turn_on: !secret loungecam_turn_on
    lounge_camera_floor: !secret loungecam_floor
  # Switches
  switch:
    - platform: command_line
      switches:
        lounge_camera_ir:
          friendly_name: Lounge Camera Night Mode
          command_on: !secret loungecam_ir_on
          command_off: !secret loungecam_ir_off
          command_state: !secret loungecam_ir_state
          value_template: '{{ value == "1" }}'
        lounge_camera_motion:
          friendly_name: Lounge Camera Motion Detection
          command_on: !secret loungecam_motion_on
          command_off: !secret loungecam_motion_off
          command_state: !secret loungecam_motion_state
          value_template: '{{ value == "1" }}'
