lounge:
  template:
    - binary_sensor:
        - name: Lounge Occupancy
          unique_id: lounge_occupancy
          device_class: occupancy
          delay_off:
            minutes: 2
          variables:
            motion: "binary_sensor.lounge_motion"
            tv: "binary_sensor.lounge_tv_state"
            door: "binary_sensor.lounge_door_contact"
            occupied_override: "input_boolean.lounge_occupied_override"
            illuminance: "sensor.lounge_illuminance"
            temperature: "sensor.lounge_temperature"
            humidity: "sensor.lounge_humidity"
          state: >
            {% set confidence_score = state_attr('binary_sensor.lounge_occupancy', 'confidence_score') | int(0) %}
            {{ confidence_score >= 20 }}
          attributes:
            confidence_score: >
              {# Define all scoring conditions in a list #}
              {% set scoring_conditions = [
                {'entity_id': motion, 'type': 'state', 'state': 'on', 'score': 40},
                {'entity_id': tv, 'type': 'state', 'state': 'on', 'score': 40},
                {'entity_id': door, 'type': 'state', 'state': 'off', 'score': 20},
                {'entity_id': occupied_override, 'type': 'state', 'state': 'on', 'score': 50},
                {'entity_id': illuminance, 'type': 'range', 'min': 0, 'max': 100, 'score': 10},
                {'entity_id': temperature, 'type': 'range', 'min': 18, 'max': 25, 'score': 10},
                {'entity_id': humidity, 'type': 'range', 'min': 30, 'max': 60, 'score': 10}
              ] %}

              {# Initialise the scores and active contributors #}
              {% set scores = namespace(total=0) %}

              {# Loop through each scoring condition #}
              {% for condition in scoring_conditions %}
                {% if condition.type == 'state' %}
                  {# Check if the entity matches the expected state #}
                  {% if is_state(condition.entity_id, condition.state) %}
                    {% set scores.total = scores.total + condition.score %}
                  {% endif %}
                {% elif condition.type == 'range' %}
                  {# Check if the entity value falls within the specified range #}
                  {% set value = states(condition.entity_id) | float(0) %}
                  {% if value >= condition.min and value <= condition.max %}
                    {% set scores.total = scores.total + condition.score %}
                  {% endif %}
                {% endif %}
              {% endfor %}

              {# Calculate the maximum score dynamically #}
              {% set max_score = scoring_conditions | map(attribute='score') | sum %}
              {# Calculate the percentage score, rounded to the nearest whole number #}
              {% set percentage = (scores.total / max_score * 100) | round(0) %}
              {# Output final percentage #}
              {{ percentage }}
  input_boolean:
    lounge_occupied_override:
      name: Lounge Manual Occupancy Override
      icon: mdi:account-check
    lounge_sleep_mode:
      name: Lounge Sleep Mode
      icon: mdi:power-sleep
    lounge_automations:
      name: Lounge Automations
      icon: mdi:robot

  media_player:
    - platform: wiim_custom
      host: 192.168.1.250
      name: Lounge Speakers Wiim
      uuid: 'FF98F09CAA6BA405CDE17CF2'

    - platform: universal
      name: Lounge Speakers
      browse_media_entity: media_player.lounge_speakers_wiim
      device_class: speaker
      unique_id: lounge_speakers
      children:
        - media_player.lounge_speakers_wiim
        - media_player.lounge_speakers_cast
        - media_player.lounge_speakers_alexa
        - media_player.lounge_speakers_dlna
        - media_player.lounge_speakers_ma
      commands:
        turn_on:
          service: media_player.turn_on
          target:
            entity_id: media_player.lounge_speakers_cast
        turn_off:
          service: media_player.media_stop
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_up:
          service: media_player.volume_up
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_down:
          service: media_player.volume_down
          target:
            entity_id: media_player.lounge_speakers_wiim
        volume_mute:
          service: media_player.volume_mute
          target:
            entity_id: media_player.lounge_speakers_wiim
        select_source:
          service: media_player.select_source
          target:
            entity_id: media_player.lounge_speakers_wiim
          data:
            source: "{{ source }}"
        volume_set:
          service: media_player.volume_set
          target:
            entity_id: media_player.lounge_speakers_wiim
          data:
            volume_level: "{{ volume_level }}"
      attributes:
        source: media_player.lounge_speakers_wiim|source
        source_list: media_player.lounge_speakers_wiim|source_list
        entity_picture: media_player.lounge_speakers_wiim|entity_picture
        media_album_name: media_player.lounge_speakers_wiim|media_album_name
        media_title: media_player.lounge_speakers_wiim|media_title
        media_duration: media_player.lounge_speakers_wiim|media_duration
        media_position: media_player.lounge_speakers_wiim|media_position

    - platform: universal
      name: Lounge TV
      browse_media_entity: media_player.lounge_tv_shield
      device_class: tv
      unique_id: lounge_tv
      children:
        - media_player.lounge_tv_adb
        - media_player.lounge_tv_cast
        - media_player.lounge_tv_dlna
        - media_player.lounge_tv_shield
        - media_player.lounge_tv_shield_cast
        - media_player.lounge_tv_sony
      commands:
        turn_on:
          service: media_player.turn_on
          target:
            entity_id: media_player.lounge_tv_shield
        turn_off:
          service: media_player.media_stop
          target:
            entity_id: media_player.lounge_tv_shield
        volume_up:
          service: media_player.volume_up
          target:
            entity_id: media_player.lounge_tv_shield
        volume_down:
          service: media_player.volume_down
          target:
            entity_id: media_player.lounge_tv_shield
        volume_mute:
          service: media_player.volume_mute
          target:
            entity_id: media_player.lounge_tv_shield
        select_source:
          service: media_player.select_source
          target:
            entity_id: media_player.lounge_tv_shield
          data:
            source: "{{ source }}"
        volume_set:
          service: media_player.volume_set
          target:
            entity_id: media_player.lounge_tv_shield
          data:
            volume_level: "{{ volume_level }}"
      attributes:
        source: media_player.lounge_tv_shield|source
        source_list: media_player.lounge_tv_shield|source_list
        entity_picture: media_player.lounge_tv_shield|entity_picture
        media_album_name: media_player.lounge_tv_shield|media_album_name
        media_title: media_player.lounge_tv_shield|media_title
        media_duration: media_player.lounge_tv_shield|media_duration
        media_position: media_player.lounge_tv_shield|media_position
