front_drive:
  binary_sensor:
    - platform: bayesian
      name: Front Drive Occupied
      prior: 0.02
      device_class: occupancy
      probability_threshold: 0.7
      observations:

        - platform: "state"
          entity_id: binary_sensor.front_door_contact
          prob_given_true: 0.1527232
          prob_given_false: 0.0029303
          to_state: "off"

        - platform: "state"
          entity_id: binary_sensor.front_door_ding
          prob_given_true: 0.3561458
          prob_given_false: 0.0051928
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.front_door_motion
          prob_given_true: 0.2561890
          prob_given_false: 0.0002271
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.front_drive_motion
          prob_given_true: 0.4671964
          prob_given_false: 0.0002967
          to_state: "on"
