all_automations:
  name: All Automations
  icon: mdi:robot
  entities:
    - input_boolean.area_bathroom_automations
    - input_boolean.area_bedroom_automations
    - input_boolean.area_entrance_automations
    - input_boolean.area_hall_automations
    - input_boolean.area_home_automations
    - input_boolean.area_kitchen_automations
    - input_boolean.area_lounge_automations
    - input_boolean.area_study_automations
    - input_boolean.area_toilet_automations