all_automations:
  name: All Automations
  entities:
    - input_boolean.bathroom_automations
    - input_boolean.bedroom_automations
    - input_boolean.entrance_automations
    - input_boolean.hall_automations
    - input_boolean.home_automations
    - input_boolean.kitchen_automations
    - input_boolean.lounge_automations
    - input_boolean.study_automations
    - input_boolean.toilet_automations