alias: Room - Bedroom - Lights
id: bf065214-cd47-43f8-a537-d39686045b26
description: ""
mode: queued

trigger:
  - platform: state
    entity_id:
      - binary_sensor.area_bedroom_occupied

condition:
  - condition: state
    entity_id: input_boolean.area_bedroom_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: media_player.bedroom_tv
            state: "on"
          - condition: state
            entity_id: input_boolean.sleep_mode
            state: "off"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 20
            target:
              entity_id: light.bedroom_lights
    default:
      - condition: state
        entity_id: binary_sensor.area_bedroom_occupied
        state: "off"
        for: 00:20:00
      - service: light.turn_off
        target:
          entity_id: light.bedroom_lights
