####################################
# Bin Collection
####################################
- platform: rest
  name: Bin Collection Data
  json_attributes_path: "$.collections[0]"
  json_attributes:
    - date
    - roundTypes
    - slippedCollection
  value_template: >
    {% set map = {"RECYCLE": "blue", "DOMESTIC": "black", "ORGANIC": "green"} %}
    {{ "The " }}
    {%- for type in value_json.collections[0].roundTypes -%}
      {%- if loop.length > 1 -%}
        {%- if loop.first -%}
          {{map[type]}}
        {%- elif loop.last -%}
          {{ " and " }}{{map[type]}}
        {%- else -%}
          {{ ", " }}{{map[type]}}
        {%- endif -%}
      {%- else -%}
        {{map[type]}}
      {%- endif -%}
    {%- endfor -%}
    {{strptime(value_json.collections[0].date,"%Y-%m-%dT%H:%M:%SZ").strftime(" bin will be collected on %A, %b %d")}}
  resource: !secret bin_collection