####################################
# Energy
####################################
- platform: "octopusagile"
- platform: rest
  name: Gas Daily Usage
  device_class: power
  unit_of_measurement: "kWh"
  json_attributes_path: "$.results[1]"
  json_attributes:
    - interval_start
    - interval_end
  value_template: "{{value_json.results[1].consumption}}"
  resource: !secret octopus_gas
- platform: rest
  name: Electricity Daily Usage
  device_class: power
  unit_of_measurement: "kWh"
  json_attributes_path: "$.results[1]"
  json_attributes:
    - interval_start
    - interval_end
  value_template: "{{value_json.results[1].consumption}}"
  resource: !secret octopus_electricity