- platform: mqtt_room
  device_id: ble-f918c94530f3
  name: Laura Versa 2 MQTT Room Presence
  state_topic: mqtt-room
- platform: mqtt_room
  device_id: ble-60e83ce863c04d5ba5ad427f1277365b-100-1
  name: Seb Phone MQTT Room Presence
  state_topic: mqtt-room
- platform: mqtt_room
  device_id: ble-ca16c924c7714d6d855dd590ab02e152-100-1
  name: Laura Phone 2 MQTT Room Presence
  state_topic: mqtt-room