####################################
# Probabilities
####################################
- platform: template
  sensors:
    bathroom_occupied_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.bathroom_occupied','probability')*100 | int }}"
    study_occupied_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.study_occupied','probability')*100 | int }}"
    lounge_occupied_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.lounge_occupied','probability')*100 | int }}"
    hall_occupied_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.hall_occupied','probability')*100 | int }}"
    toilet_occupied_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.toilet_occupied','probability')*100 | int }}"
    kitchen_occupied_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.kitchen_occupied','probability')*100 | int }}"
    bedroom_occupied_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.bedroom_occupied','probability')*100 | int }}"
    entrance_occupied_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.entrance_occupied','probability')*100 | int }}"
    in_bed_probability:
      unit_of_measurement: "%"
      value_template: "{{ state_attr('binary_sensor.in_bed','probability')*100 | int }}"