####################################
# Statistics Sensors
####################################

####################################
# Temperature
####################################
- platform: statistics
  name: "Bathroom Temperature Statistics"
  max_age:
    days: 1
  entity_id: sensor.bathroom_temperature

- platform: statistics
  name: "Bedroom Temperature Statistics"
  max_age:
    days: 1
  entity_id: sensor.bedroom_temperature

- platform: statistics
  name: "Central Temperature Statistics"
  max_age:
    days: 1
  entity_id: sensor.central_temperature

- platform: statistics
  name: "Hall Temperature Statistics"
  max_age:
    days: 1
  entity_id: sensor.hall_trisensor_air_temperature

- platform: statistics
  name: "Kitchen Temperature Statistics"
  max_age:
    days: 1
  entity_id: sensor.kitchen_trisensor_air_temperature

- platform: statistics
  name: "Lounge Temperature Statistics"
  max_age:
    days: 1
  entity_id: sensor.lounge_trisensor_air_temperature

- platform: statistics
  name: "Study Temperature Statistics"
  max_age:
    days: 1
  entity_id: sensor.study_temperature

- platform: statistics
  name: "Toilet Temperature Statistics"
  max_age:
    days: 1
  entity_id: sensor.toilet_temperature

####################################
# Luminance
####################################
- platform: statistics
  name: "Bathroom Illuminance Statistics"
  max_age:
    days: 1
  entity_id: sensor.bathroom_multisensor_illuminance

- platform: statistics
  name: "Bedroom Illuminance Statistics"
  max_age:
    days: 1
  entity_id: sensor.bedroom_trisensor_illuminance

- platform: statistics
  name: "Hall Illuminance Statistics"
  max_age:
    days: 1
  entity_id: sensor.hall_trisensor_illuminance

- platform: statistics
  name: "Kitchen Illuminance Statistics"
  max_age:
    days: 1
  entity_id: sensor.kitchen_trisensor_illuminance

- platform: statistics
  name: "Lounge Illuminance Statistics"
  max_age:
    days: 1
  entity_id: sensor.lounge_trisensor_illuminance

- platform: statistics
  name: "Study Illuminance Statistics"
  max_age:
    days: 1
  entity_id: sensor.study_trisensor_illuminance

- platform: statistics
  name: "Toilet Illuminance Statistics"
  max_age:
    days: 1
  entity_id: sensor.toilet_trisensor_illuminance

####################################
# Humidity
####################################
- platform: statistics
  name: "Bathroom Humidity Statistics"
  max_age:
    days: 1
  entity_id: sensor.bathroom_multisensor_humidity

####################################
# Ratios
####################################
# Entrance
- platform: history_stats
  name: "Ratio Entrance Dog Motion"
  entity_id: binary_sensor.entrance_dog_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Entrance Person Motion"
  entity_id: binary_sensor.entrance_person_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Entrance Door Open"
  entity_id: binary_sensor.entrance_door
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Entrance Door Motion"
  entity_id: binary_sensor.front_door_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Entrance Door Ding"
  entity_id: binary_sensor.front_door_ding
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7

# Bathroom
- platform: history_stats
  name: "Ratio Bathroom Motion"
  entity_id: binary_sensor.bathroom_multisensor_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Shower Occupied"
  entity_id: binary_sensor.shower_occupied
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Bathroom Humidity Trend"
  entity_id: binary_sensor.bathroom_humidity_trend
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Bathroom Temperature Trend"
  entity_id: binary_sensor.bathroom_temperature_trend
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7

# Bedroom
- platform: history_stats
  name: "Ratio Bedroom Motion"
  entity_id: binary_sensor.bedroom_trisensor_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Bedroom Person Motion"
  entity_id: binary_sensor.bedroom_person_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Bedroom Dog Motion"
  entity_id: binary_sensor.bedroom_person_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Seb Bedroom Presence"
  entity_id: sensor.seb_phone_ble_room_presence
  state: "Bedroom"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Laura Bedroom Presence"
  entity_id: sensor.laura_phone_ble_room_presence
  state: "Bedroom"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Laura Sleeping"
  entity_id: binary_sensor.laura_sleeping
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Seb Sleeping"
  entity_id: binary_sensor.seb_sleeping
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7

# Hall
- platform: history_stats
  name: "Ratio Hall Motion"
  entity_id: binary_sensor.hall_trisensor_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Hall Dog Motion"
  entity_id: binary_sensor.hall_dog_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Hall Person Motion"
  entity_id: binary_sensor.hall_person_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7

# Kitchen
- platform: history_stats
  name: "Ratio Kitchen Motion"
  entity_id: binary_sensor.kitchen_trisensor_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Seb Kitchen Presence"
  entity_id: sensor.seb_phone_ble_room_presence
  state: "Kitchen"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Laura Kitchen Presence"
  entity_id: sensor.laura_phone_ble_room_presence
  state: "Kitchen"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Kitchen Dog Motion"
  entity_id: binary_sensor.kitchen_dog_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Kitchen Person Motion"
  entity_id: binary_sensor.kitchen_person_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7

# Lounge
- platform: history_stats
  name: "Ratio Lounge Motion"
  entity_id: binary_sensor.lounge_trisensor_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Seb Lounge Presence"
  entity_id: sensor.seb_phone_ble_room_presence
  state: "Lounge"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Laura Lounge Presence"
  entity_id: sensor.laura_phone_ble_room_presence
  state: "Lounge"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Lounge Dog Motion"
  entity_id: binary_sensor.lounge_dog_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Lounge Person Motion"
  entity_id: binary_sensor.lounge_person_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7

# Stairs
- platform: history_stats
  name: "Ratio Stairs Dog Motion"
  entity_id: binary_sensor.stairs_dog_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Stairs Person Motion"
  entity_id: binary_sensor.stairs_person_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7


# Study
- platform: history_stats
  name: "Ratio Seb PC Active"
  entity_id: binary_sensor.seb_pc_active
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Study Motion"
  entity_id: binary_sensor.study_trisensor_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Seb Study Presence"
  entity_id: sensor.seb_phone_ble_room_presence
  state: "Study"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Laura Study Presence"
  entity_id: sensor.laura_phone_ble_room_presence
  state: "Study"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Study Dog Motion"
  entity_id: binary_sensor.study_dog_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
- platform: history_stats
  name: "Ratio Study Person Motion"
  entity_id: binary_sensor.study_person_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7

# Toilet
- platform: history_stats
  name: "Ratio Toilet Motion"
  entity_id: binary_sensor.toilet_trisensor_motion
  state: "on"
  type: ratio
  end: "{{ now() }}"
  duration:
    days: 7
