####################################
# Bayesian Sensors
####################################
# Bathroom
- platform: bayesian
  name: Area - Bathroom Occupied
  prior: 0.2083
  device_class: occupancy
  probability_threshold: 0.70
  observations:
    - platform: "state"
      entity_id: "binary_sensor.area_bathroom_humidity_trend"
      prob_given_true: 0.0768
      prob_given_false: 0.0020
      to_state: "on"
    - platform: "state"
      entity_id: "group.area_bathroom_motion"
      prob_given_true: 0.6720
      prob_given_false: 0.0531
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.area_bathroom_bright"
      prob_given_true: 1.2048
      prob_given_false: 0.2853
      to_state: "on"
    - platform: "state"
      entity_id: "input_boolean.bathroom_schedule"
      prob_given_true: 0.3840
      prob_given_false: 0.0707
      to_state: "on"

# Bedroom
- platform: bayesian
  name: Area - Bedroom Occupied
  prior: 0.5
  device_class: occupancy
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "media_player.bedroom_tv"
      prob_given_true: 0.0300
      prob_given_false: 0.0015
      to_state: "playing"
    - platform: "state"
      entity_id: "binary_sensor.laura_sleeping"
      prob_given_true: 0.5940
      prob_given_false: 0.0891
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.seb_sleeping"
      prob_given_true: 0.9680
      prob_given_false: 0.1452
      to_state: "on"
    - platform: "state"
      entity_id: "media_player.bedroom_echo"
      prob_given_true: 0.0720
      prob_given_false: 0.0144
      to_state: "playing"
    - platform: "state"
      entity_id: "input_boolean.sleep_schedule"
      prob_given_true: 0.8
      prob_given_false: 0.16
      to_state: "on"
    - platform: "state"
      entity_id: "group.area_bedroom_motion"
      prob_given_true: 0.1960
      prob_given_false: 0.0392
      to_state: "on"
    - platform: "state"
      entity_id: "input_boolean.bedroom_schedule"
      prob_given_true: 0.9400
      prob_given_false: 0.3290
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.area_bedroom_bright"
      prob_given_true: 0.4040
      prob_given_false: 0.3838
      to_state: "on"
    - platform: "state"
      entity_id: "sun.sun"
      prob_given_true: 0.98
      prob_given_false: 0.6860
      to_state: "below_horizon"

- platform: bayesian
  name: "Bed Occupied"
  prior: 0.42
  device_class: occupancy
  probability_threshold: 0.9
  observations:
    - platform: "state"
      entity_id: "group.area_bedroom_motion"
      prob_given_true: 0.11
      prob_given_false: 0.0267
      to_state: "on"
    - platform: "state"
      entity_id: "input_boolean.sleep_schedule"
      prob_given_true: 0.93
      prob_given_false: 0.173
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.seb_sleeping"
      prob_given_true: 0.8
      prob_given_false: 0.0667
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.laura_sleeping"
      prob_given_true: 0.8
      prob_given_false: 0.0667
      to_state: "on"
    - platform: "state"
      entity_id: "sun.sun"
      prob_given_true: 0.99
      prob_given_false: 0.2
      to_state: "below_horizon"
    - platform: "state"
      entity_id: "media_player.bedroom_echo"
      prob_given_true: 0.11
      prob_given_false: 0.0333
      to_state: "playing"
    - platform: "state"
      entity_id: "media_player.bedroom_tv"
      prob_given_true: 0.21
      prob_given_false: 0.0667
      to_state: "playing"

# Entrance
- platform: bayesian
  name: Area - Entrance Occupied
  prior: 0.0208
  device_class: occupancy
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.dor_03_contact"
      prob_given_true: 0.0960
      prob_given_false: 0.0001
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.people_entrance"
      prob_given_true: 0.9600
      prob_given_false: 0.0010
      to_state: "on"
    - platform: "state"
      entity_id: "group.area_entrance_motion"
      prob_given_true: 0.9600
      prob_given_false: 0.0020
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.front_door_motion"
      prob_given_true: 0.0480
      prob_given_false: 0.0007
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.area_entrance_bright"
      prob_given_true: 16.8
      prob_given_false: 0.3217
      to_state: "on"

# Hall
- platform: bayesian
  name: Area - Hall Occupied
  prior: 0.02
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "group.area_hall_motion"
      prob_given_true: 0.96
      prob_given_false: 0.004
      to_state: "on"

# Kitchen
- platform: bayesian
  name: Area - Kitchen Occupied
  prior: 0.13
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "group.area_kitchen_motion"
      prob_given_true: 0.96
      prob_given_false: 0.014
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.area_kitchen_people"
      prob_given_true: 0.46
      prob_given_false: 0.01
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.area_kitchen_temperature_trend"
      prob_given_true: 0.16
      prob_given_false: 0.048
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.kitchen_schedule"
      prob_given_true: 0.16
      prob_given_false: 0.048
      to_state: "on"

# Lounge
- platform: bayesian
  name: Area - Lounge Occupied
  prior: 0.29
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "group.area_lounge_motion"
      prob_given_true: 0.25
      prob_given_false: 0.0176
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.area_lounge_people"
      prob_given_true: 0.59
      prob_given_false: 0.0294
      to_state: "on"
    - platform: "state"
      entity_id: "media_player.lounge_tv"
      prob_given_true: 0.59
      prob_given_false: 0.0294
      to_state: "playing"

# Study
- platform: bayesian
  name: Area - Study Occupied
  prior: 0.33
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "group.area_study_motion"
      prob_given_true: 0.43
      prob_given_false: 0.0187
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.starrunner_active"
      prob_given_true: 0.77
      prob_given_false: 0.0938
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.people_study"
      prob_given_true: 0.01
      prob_given_false: 0.0006
      to_state: "on"

# Toilet
- platform: bayesian
  name: Area - Toilet Occupied
  prior: 0.02
  device_class: occupancy
  probability_threshold: 0.6
  observations:
    - platform: "state"
      entity_id: "group.area_toilet_motion"
      prob_given_true: 0.48
      prob_given_false: 0.0043
      to_state: "on"

