####################################
# Bright Sensors
####################################
####################################
# Bright Binary Sensors
####################################
- platform: template
  sensors:
    study_bright:
      friendly_name: "Study Bright"
      device_class: light
      value_template: >-
        {{ (states('sensor.study_trisensor_illuminance') | float) >= (states('input_number.study_lux_level') | float) }}
    hall_bright:
      friendly_name: "Hall Bright"
      device_class: light
      value_template: >-
        {{ (states('sensor.hall_trisensor_illuminance') | float) >= (states('input_number.hall_lux_level') | float) }}
    bedroom_bright:
      friendly_name: "Bedroom Bright"
      device_class: light
      value_template: >-
        {{ (states('sensor.bedroom_trisensor_illuminance') | float) >= (states('input_number.bedroom_lux_level') | float) }}
    bathroom_bright:
      friendly_name: "Bathroom Bright"
      device_class: light
      value_template: >-
        {{ (states('sensor.bathroom_multisensor_illuminance') | float) >= (states('input_number.bathroom_lux_level') | float) }}
    kitchen_bright:
      friendly_name: "Kitchen Bright"
      device_class: light
      value_template: >-
        {{ (states('sensor.kitchen_trisensor_illuminance') | float) >= (states('input_number.kitchen_lux_level') | float) }}
    lounge_bright:
      friendly_name: "Lounge Bright"
      device_class: light
      value_template: >-
        {{ (states('sensor.lounge_trisensor_illuminance') | float) >= (states('input_number.lounge_lux_level') | float) }}
    toilet_bright:
      friendly_name: "Toilet Bright"
      device_class: light
      value_template: >-
        {{ (states('sensor.toilet_trisensor_illuminance') | float) >= (states('input_number.toilet_lux_level') | float) }}