####################################
# MQTT
####################################
- platform: mqtt
  name: Seb PC Online
  state_topic: homeassistant/sensor/STARRUNNER/availability
  payload_on: "online"
  payload_off: "offline"
  device_class: connectivity

####################################
# People
####################################
- platform: mqtt
  name: People Entrance
  availability_topic: frigate/available
  state_topic: "frigate/Area - Entrance/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: People Hall
  availability_topic: frigate/available
  state_topic: "frigate/Area - Hall/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: People Kitchen
  availability_topic: frigate/available
  state_topic: "frigate/Area - Kitchen/person"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: People Lounge
  availability_topic: frigate/available
  state_topic: "frigate/Area - Lounge/person"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: People Stairs
  availability_topic: frigate/available
  state_topic: "frigate/Area - Stairs/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

####################################
# Dogs
####################################
- platform: mqtt
  name: Dogs Entrance
  availability_topic: frigate/available
  state_topic: "frigate/Area - Entrance/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Dogs Hall
  availability_topic: frigate/available
  state_topic: "frigate/Area - Hall/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Dogs Kitchen
  availability_topic: frigate/available
  state_topic: "frigate/Area - Kitchen/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Dogs Lounge
  availability_topic: frigate/available
  state_topic: "frigate/Area - Lounge/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Dogs Stairs
  availability_topic: frigate/available
  state_topic: "frigate/Area - Stairs/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"