####################################
# MQTT
####################################
- platform: mqtt
  name: Starrunner Online
  state_topic: homeassistant/sensor/STARRUNNER/availability
  payload_on: "online"
  payload_off: "offline"
  device_class: connectivity

####################################
# People
####################################
- platform: mqtt
  name: Zone - Entrance People
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Entrance/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Zone - Hall People
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Hall/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Zone - Kitchen People
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Kitchen/person"
  device_class: motion
  off_delay: 180
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Zone - Lounge People
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Lounge/person"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Zone - Stairs People
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Stairs/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

####################################
# Dogs
####################################
- platform: mqtt
  name: Zone - Entrance Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Entrance/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Zone - Hall Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Hall/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Zone - Kitchen Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Kitchen/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Zone - Lounge Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Lounge/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Zone - Stairs Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Zone - Stairs/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"