####################################
# MQTT
####################################
- platform: mqtt
  name: Starrunner Online
  state_topic: homeassistant/sensor/STARRUNNER/availability
  payload_on: "online"
  payload_off: "offline"
  device_class: connectivity

####################################
# People
####################################
- platform: mqtt
  name: Area - Entrance People
  availability_topic: frigate/available
  state_topic: "frigate/Area - Entrance/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Area - Hall People
  availability_topic: frigate/available
  state_topic: "frigate/Area - Hall/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Area - Kitchen People
  availability_topic: frigate/available
  state_topic: "frigate/Area - Kitchen/person"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Area - Lounge People
  availability_topic: frigate/available
  state_topic: "frigate/Area - Lounge/person"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Area - Stairs People
  availability_topic: frigate/available
  state_topic: "frigate/Area - Stairs/person"
  device_class: motion
  off_delay: 30
  value_template: "{% if value_json > 0 %}ON{% endif %}"

####################################
# Dogs
####################################
- platform: mqtt
  name: Area - Entrance Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Area - Entrance/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Area - Hall Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Area - Hall/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Area - Kitchen Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Area - Kitchen/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Area - Lounge Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Area - Lounge/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"

- platform: mqtt
  name: Area - Stairs Dogs
  availability_topic: frigate/available
  state_topic: "frigate/Area - Stairs/dog"
  device_class: motion
  off_delay: 60
  value_template: "{% if value_json > 0 %}ON{% endif %}"