# ####################################
# # Presence Binary Sensors
# ####################################
# ####################################
# # People Home Binary Sensors
# ####################################
# # - platform: template
# #   sensors:
# #     people_home:
# #       friendly_name: "People Home"
# #       icon_template: "mdi:home"
# #       device_class: presence
# #       value_template: >-
# #         {{ is_state('person.laura_ward', 'home') or is_state('person.sebastian_burrell', 'home') }}

# ####################################
# # Bayesian Sensors
# ####################################
- platform: bayesian
  name: "Kitchen Occupied"
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: "template"
      value_template: "{{ (states('sensor.bathroom_multisensor_humidity_air')| float > (states('sensor.bathroom_average_humidity')| float + states('input_number.bathroom_humidity_offset')| float)) }}"
      prob_given_true: 0.7
      prob_given_false: 0.3
    - platform: "state"
      entity_id: "binary_sensor.bathroom_humidity_trend"
      prob_given_true: 0.7
      prob_given_false: 0.3
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.bathroom_multisensor_motion"
      prob_given_true: 1
      prob_given_false: 0.2
      to_state: "on"

- platform: bayesian
  name: "Kitchen Occupied"
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.kitchen_trisensor_motion"
      prob_given_true: 0.7
      prob_given_false: 0.3
      to_state: "on"

- platform: bayesian
  name: "Lounge Occupied"
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.lounge_motion_camera"
      prob_given_true: 0.75
      prob_given_false: 0.5
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.lounge_trisensor_motion"
      prob_given_true: 0.99
      prob_given_false: 0.5
      to_state: "on"
    - platform: "state"
      entity_id: "media_player.lounge_tv"
      prob_given_true: 0.8
      prob_given_false: 0.5
      to_state: "playing"
    - platform: "state"
      entity_id: "binary_sensor.lounge_motion_camera_tapo"
      prob_given_true: 0.7
      prob_given_false: 0.2
      to_state: "on"

- platform: bayesian
  name: "Hall Occupied"
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.hall_motion_camera"
      prob_given_true: 0.8
      prob_given_false: 0.2
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.hall_trisensor_motion"
      prob_given_true: 0.99
      prob_given_false: 0.4
      to_state: "on"

- platform: bayesian
  name: "Entrance Occupied"
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.entrance_motion_camera"
      prob_given_true: 0.4
      prob_given_false: 0.2
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.front_door_motion"
      prob_given_true: 0.4
      prob_given_false: 0.2
      to_state: "on"

- platform: bayesian
  name: "Bedroom Occupied"
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.bedroom_trisensor_motion"
      prob_given_true: 0.4
      prob_given_false: 0.2
      to_state: "on"

- platform: bayesian
  name: "Study Occupied"
  prior: 0.42
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "binary_sensor.study_trisensor_motion"
      prob_given_true: 0.6
      prob_given_false: 0.07
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.starrunner_active"
      prob_given_true: 0.9
      prob_given_false: 0.07
      to_state: "on"

- platform: bayesian
  name: "Bathroom Occupied"
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.shower_occupied"
      prob_given_true: 1
      prob_given_false: 0.6
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.bathroom_multisensor_motion"
      prob_given_true: 1
      prob_given_false: 0.2
      to_state: "on"

- platform: bayesian
  name: "Toilet Occupied"
  prior: 0.5
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.toilet_trisensor_motion"
      prob_given_true: 1
      prob_given_false: 0.2
      to_state: "on"

- platform: bayesian
  name: "In Bed"
  prior: 0.25
  probability_threshold: 0.95
  observations:
    - platform: "state"
      entity_id: "sensor.lounge_trisensor_motion"
      prob_given_true: 0.4
      prob_given_false: 0.2
      to_state: "off"
    - platform: "state"
      entity_id: "sensor.kitchen_trisensor_motion"
      prob_given_true: 0.5
      prob_given_false: 0.4
      to_state: "off"
    - platform: "state"
      entity_id: "sensor.bedroom_trisensor_motion"
      prob_given_true: 0.5
      to_state: "on"
    - platform: "state"
      entity_id: "sun.sun"
      prob_given_true: 0.7
      to_state: "below_horizon"
