####################################
# Presence Binary Sensors
####################################
- platform: template
  sensors:
    shower_occupied:
      friendly_name: "Shower Occupied"
      device_class: occupancy
      value_template: >-
        {{ (states('sensor.bathroom_multisensor_humidity')| float > (states('sensor.bathroom_humidity_statistics')| float + states('input_number.bathroom_humidity_offset')| float)) and states('binary_sensor.bathroom_humidity_trend') }}

####################################
# People Home Binary Sensors
####################################
- platform: template
  sensors:
    people_home:
      friendly_name: "People Home"
      icon_template: "mdi:home"
      device_class: presence
      value_template: >-
        {{ is_state('person.laura_ward', 'home') or is_state('person.sebastian_burrell', 'home') }}

####################################
# Sleeping Binary Sensors
####################################
- platform: template
  sensors:
    laura_sleeping:
      friendly_name: "Laura Sleeping"
      icon_template: "mdi:sleep"
      value_template: "{{ states('sensor.laura_phone_sleep_confidence') | int > 90 }}"
    seb_sleeping:
      friendly_name: "Seb Sleeping"
      icon_template: "mdi:sleep"
      value_template: "{{ states('sensor.seb_phone_sleep_confidence') | int > 90 }}"

####################################
# Bayesian Sensors
####################################
# Bathroom
- platform: bayesian
  name: "Bathroom Occupied"
  prior: 0.2083
  device_class: occupancy
  probability_threshold: 0.70
  observations:
    - platform: "state"
      entity_id: "binary_sensor.bathroom_humidity_trend"
      prob_given_true: 0.0768
      prob_given_false: 0.0020
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.bathroom_multisensor_motion"
      prob_given_true: 0.6720
      prob_given_false: 0.0531
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.bathroom_bright"
      prob_given_true: 1.2048
      prob_given_false: 0.2853
      to_state: "on"
    - platform: "state"
      entity_id: "input_boolean.bathroom_schedule"
      prob_given_true: 0.3840
      prob_given_false: 0.0707
      to_state: "on"

# Bedroom
- platform: bayesian
  name: "Bedroom Occupied"
  prior: 0.5
  device_class: occupancy
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "media_player.bedroom_tv"
      prob_given_true: 0.0300
      prob_given_false: 0.0015
      to_state: "playing"
    - platform: "state"
      entity_id: "binary_sensor.laura_sleeping"
      prob_given_true: 0.5940
      prob_given_false: 0.0891
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.seb_sleeping"
      prob_given_true: 0.9680
      prob_given_false: 0.1452
      to_state: "on"
    - platform: "state"
      entity_id: "media_player.bedroom_echo"
      prob_given_true: 0.0720
      prob_given_false: 0.0144
      to_state: "playing"
    - platform: "state"
      entity_id: "input_boolean.sleep_schedule"
      prob_given_true: 0.8
      prob_given_false: 0.16
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.bedroom_trisensor_motion"
      prob_given_true: 0.1960
      prob_given_false: 0.0392
      to_state: "on"
    - platform: "state"
      entity_id: "sensor.laura_phone_ble_room_presence"
      prob_given_true: 1.1720
      prob_given_false: 0.4102
      to_state: "Bedroom"
    - platform: "state"
      entity_id: "input_boolean.bedroom_schedule"
      prob_given_true: 0.9400
      prob_given_false: 0.3290
      to_state: "on"
    - platform: "state"
      entity_id: "sensor.seb_phone_ble_room_presence"
      prob_given_true: 1.32
      prob_given_false: 0.5940
      to_state: "Bedroom"
    - platform: "state"
      entity_id: "binary_sensor.people_bedroom"
      prob_given_true: 0.0002
      prob_given_false: 0.0001
      to_state: "on"
    - platform: "state"
      entity_id: "sun.sun"
      prob_given_true: 0.98
      prob_given_false: 0.6860
      to_state: "below_horizon"
    - platform: "state"
      entity_id: "binary_sensor.bedroom_bright"
      prob_given_true: 0.4040
      prob_given_false: 0.3838
      to_state: "on"

- platform: bayesian
  name: "In Bed"
  prior: 0.42
  device_class: occupancy
  probability_threshold: 0.9
  observations:
    - platform: "state"
      entity_id: "binary_sensor.bedroom_trisensor_motion"
      prob_given_true: 0.11
      prob_given_false: 0.0267
      to_state: "on"
    - platform: "state"
      entity_id: "input_boolean.sleep_schedule"
      prob_given_true: 0.93
      prob_given_false: 0.173
      to_state: "on"
    - platform: "state"
      entity_id: "sensor.Laura_phone_ble_room_presence"
      prob_given_true: 0.96
      prob_given_false: 0.0667
      to_state: "Bedroom"
    - platform: "state"
      entity_id: "sensor.seb_phone_ble_room_presence"
      prob_given_true: 0.96
      prob_given_false: 0.0667
      to_state: "Bedroom"
    - platform: "state"
      entity_id: "binary_sensor.seb_sleeping"
      prob_given_true: 0.8
      prob_given_false: 0.0667
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.laura_sleeping"
      prob_given_true: 0.8
      prob_given_false: 0.0667
      to_state: "on"
    - platform: "state"
      entity_id: "sun.sun"
      prob_given_true: 0.99
      prob_given_false: 0.2
      to_state: "below_horizon"
    - platform: "state"
      entity_id: "media_player.bedroom_echo"
      prob_given_true: 0.11
      prob_given_false: 0.0333
      to_state: "playing"
    - platform: "state"
      entity_id: "media_player.bedroom_tv"
      prob_given_true: 0.21
      prob_given_false: 0.0667
      to_state: "playing"

# Entrance
- platform: bayesian
  name: "Entrance Occupied"
  prior: 0.0208
  device_class: occupancy
  probability_threshold: 0.7
  observations:
    - platform: "state"
      entity_id: "binary_sensor.entrance_door"
      prob_given_true: 0.0960
      prob_given_false: 0.0001
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.people_entrance"
      prob_given_true: 0.9600
      prob_given_false: 0.0010
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.fire_tablet_motion"
      prob_given_true: 0.9600
      prob_given_false: 0.0020
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.front_door_motion"
      prob_given_true: 0.0480
      prob_given_false: 0.0007
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.entrance_bright"
      prob_given_true: 16.8
      prob_given_false: 0.3217
      to_state: "on"

# Hall
- platform: bayesian
  name: "Hall Occupied"
  prior: 0.02
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "binary_sensor.people_hall"
      prob_given_true: 0.58
      prob_given_false: 0.0085
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.hall_trisensor_motion"
      prob_given_true: 0.96
      prob_given_false: 0.004
      to_state: "on"

# Kitchen
- platform: bayesian
  name: "Kitchen Occupied"
  prior: 0.13
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "binary_sensor.kitchen_trisensor_motion"
      prob_given_true: 0.96
      prob_given_false: 0.014
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.people_kitchen"
      prob_given_true: 0.46
      prob_given_false: 0.01
      to_state: "on"
    - platform: "state"
      entity_id: "sensor.seb_phone_ble_room_presence"
      prob_given_true: 0.48
      prob_given_false: 0.021
      to_state: "Kitchen"
    - platform: "state"
      entity_id: "sensor.laura_phone_ble_room_presence"
      prob_given_true: 0.40
      prob_given_false: 0.015
      to_state: "Kitchen"
    - platform: "state"
      entity_id: "binary_sensor.kitchen_temperature_trend"
      prob_given_true: 0.16
      prob_given_false: 0.048
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.kitchen_schedule"
      prob_given_true: 0.16
      prob_given_false: 0.048
      to_state: "on"

# Lounge
- platform: bayesian
  name: "Lounge Occupied"
  prior: 0.29
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "binary_sensor.lounge_trisensor_motion"
      prob_given_true: 0.25
      prob_given_false: 0.0176
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.people_lounge"
      prob_given_true: 0.59
      prob_given_false: 0.0294
      to_state: "on"
    - platform: "state"
      entity_id: "sensor.seb_phone_ble_room_presence"
      prob_given_true: 0.23
      prob_given_false: 0.0882
      to_state: "Lounge"
    - platform: "state"
      entity_id: "sensor.laura_phone_ble_room_presence"
      prob_given_true: 0.88
      prob_given_false: 0.0588
      to_state: "Lounge"
    - platform: "state"
      entity_id: "media_player.lounge_tv"
      prob_given_true: 0.56
      prob_given_false: 0.0176
      to_state: "playing"

# Study
- platform: bayesian
  name: "Study Occupied"
  prior: 0.33
  device_class: occupancy
  probability_threshold: 0.8
  observations:
    - platform: "state"
      entity_id: "binary_sensor.study_trisensor_motion"
      prob_given_true: 0.43
      prob_given_false: 0.0187
      to_state: "on"
    - platform: "state"
      entity_id: "binary_sensor.seb_pc_active"
      prob_given_true: 0.77
      prob_given_false: 0.0938
      to_state: "on"
    - platform: "state"
      entity_id: "sensor.seb_phone_ble_room_presence"
      prob_given_true: 0.39
      prob_given_false: 0.03125
      to_state: "Study"
    - platform: "state"
      entity_id: "sensor.laura_phone_ble_room_presence"
      prob_given_true: 0.05
      prob_given_false: 0.0125
      to_state: "Study"
    - platform: "state"
      entity_id: "binary_sensor.people_study"
      prob_given_true: 0.01
      prob_given_false: 0.0006
      to_state: "on"

# Toilet
- platform: bayesian
  name: "Toilet Occupied"
  prior: 0.02
  device_class: occupancy
  probability_threshold: 0.6
  observations:
    - platform: "state"
      entity_id: "binary_sensor.toilet_trisensor_motion"
      prob_given_true: 0.48
      prob_given_false: 0.0043
      to_state: "on"

