# ####################################
# # System Binary Sensors
# ####################################
- platform: template
  sensors:
    ####################################
    # PC Active Sensors
    ####################################
    seb_pc_active:
      friendly_name: "Seb PC Active"
      device_class: connectivity
      value_template: >-
        {% if is_state('binary_sensor.seb_pc_online', 'off' ) %}
          'off'
        {% else %}
          {{ states('sensor.time_since_pc_last_active') | int < 5 }}
        {% endif %}
