# ####################################
# # Trend Binary Sensors
# ####################################
- platform: trend
  sensors:
    bathroom_humidity_trend:
      entity_id: sensor.bathroom_multisensor_humidity_air
      sample_duration: 1200
      device_class: moisture
- platform: trend
  sensors:
    bathroom_temperature_trend:
      entity_id: sensor.bathroom_temperature
      sample_duration: 1200
      device_class: heat
