# Use this file to store secrets like usernames and passwords.
# Learn more at https: ""
####################################
# Logins
####################################
# Ring
ring_username: ""
ring_password: ""
# Hive
hive_username: ""
hive_password: ""
# Amazon
amazon_username: ""
amazon_password: ""
# Unifi
unifi_user: ""
unifi_password: ""
# Camera Admin
cam_user: ""
cam_password: ""
# samba
samba_username: ""
samba_password: ""
# MQTT Shinobi
mqtt_shinobi_username: ""
mqtt_shinobi_password: ""
# MQTT Hass Workstation
mqtt_hass_username: ""
mqtt_hass_password: ""
# MQTT Home Assistant
mqtt_ha_username: ""
mqtt_ha_password: ""
####################################
# Tokens and Secrets
####################################
octopus_auth: ""
github_username: ""
github_email: ""
github_token: ""
github_access_token: ""
spotify_clientid: ""
spotify_secret: ""
alpha_vantage_api: ""
####################################
# Rest Endpoints
####################################
octopus_gas: ""
octopus_electricity: ""
bin_collection: ""
####################################
# Device Addresses
####################################
loungecam_turn_off: ""
loungecam_turn_on: ""
loungecam_floor: ""
hallcam_turn_off: ""
hallcam_turn_on: ""
hallcam_bedroom: ""
hallcam_study: ""
hallcam_landing: ""
hallcam_stairs: ""
hallcam_ir_on: ""
hallcam_ir_off: ""
hallcam_ir_state: ""
hallcam_motion_on: ""
hallcam_motion_off: ""
hallcam_motion_state: ""
loungecam_ir_on: ""
loungecam_ir_off: ""
loungecam_ir_state: ""
loungecam_motion_on: ""
loungecam_motion_off: ""
loungecam_motion_state: ""
cam_lounge_rtsp: ""
cam_kitchen_rtsp: ""
cam_lounge_shinobi: ""
cam_kitchen_shinobi: ""
cam_hall_shinobi: ""
cam_entrance_shinobi: ""
unifi_cloud_key: ""
cam_lounge: ""
cam_kitchen: ""
cam_hall: ""
cam_entrance: ""
pisces-1: ""
pisces-2: ""
pisces-3: ""
pisces-4: ""
bedroom_fire_tv: ""
shield_tv: ""
lounge_tv: ""
adb_server_ip: ""
panasonic_tv: ""
starrunner_2gb: ""
starrunner_1gb: ""
starrunner_wifi: ""
endeavor_1gb: ""
####################################
# Config Variables
####################################
octopus_region: ""
octopus_mpan: ""
octopus_serial: ""