alias: Tracking - Get Update
id: 3aa1a27d-3000-45db-a702-febdf4f9ac37
trigger:
  - minutes: /15
    platform: time_pattern
action:
  - data:
      message: request_location_update
    service: notify.mobile_app_seb_phone
mode: single
