alias: System - Dismiss Persistant Notification
id: c43b66fa-f81a-46ee-a65a-80c3764e89bc
description: ""
mode: single

trigger:
  - platform: state
    entity_id: persistent_notification.config_entry_discovery
    to: notifying
  - platform: homeassistant
    event: start

condition: []

action:
  - service: persistent_notification.dismiss
    data:
      notification_id: config_entry_discovery
