alias: System - Shutdown Notification
id: 761953d0-50cc-4f0b-81ff-3f305223ce38
description: Send notification on Home Assistant stop
mode: single
trigger:
  - platform: homeassistant
    event: shutdown
action:
  - service: notify.mobile_app_seb_phone
    data:
      message: Home Assistant is shutting down... Bye!