alias: System - Start Notification
id: 104463f6-7524-48d9-bbe5-2bb09017e946
description: Send notification on Home Assistant start
mode: single
trigger:
  platform: homeassistant
  event: start
action:
  - service: notify.mobile_app_seb_phone
    data:
      message: Home Assistant is starting up again 🎉