alias: Home - Toggle All Automations
id: 8cea3b4f-cca1-488d-a3d4-57dc12138b0e
description: ""
mode: queued

trigger:
  - entity_id: binary_sensor.people_home
    platform: state

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.people_home
            state: "on"
        sequence:
          - scene: scene.all_on
    default:
      - scene: scene.all_off
      - data: {}
        entity_id: media_player.bedroom_tv,media_player.lounge_tv
        service: media_player.turn_off
