alias: Home - Update Climate
id: 62a3a9a9-7d97-4294-a199-42e3a49d7856
description: ""
mode: queued

trigger:
  - platform: state
    entity_id: binary_sensor.people_home
    to: "on"
  - platform: state
    entity_id: input_number.target_temperature

condition:
  - condition: state
    entity_id: binary_sensor.people_home
    state: "on"

action:
  - service: climate.turn_on
    data: {}
    entity_id: climate.central
  - service: climate.set_temperature
    data:
      entity_id: climate.central
      temperature: 19
      hvac_mode: heat
  - service: climate.set_temperature
    data:
      entity_id: climate.study
      temperature: "{{ states('input_number.target_temperature') | float }}"
      hvac_mode: heat
  - service: climate.set_temperature
    data:
      entity_id: climate.bedroom
      temperature: "{{ states('input_number.target_temperature') | float }}"
      hvac_mode: heat
  - service: climate.set_temperature
    data:
      entity_id: climate.bathroom
      temperature: "{{ states('input_number.target_temperature') | float }}"
      hvac_mode: heat
  - service: climate.set_temperature
    data:
      entity_id: climate.toilet
      temperature: 10
      hvac_mode: heat
