alias: Home - Rubbish Collection Reminder
id: d0cf70f1-cd8e-43ca-af88-d12a8a0ee241
description: ""
mode: single

trigger:
  - platform: template
    value_template:
      "{{ is_state('sensor.date_time', (strptime(state_attr('sensor.bin_collection_data',
      'date'),'%Y-%m-%dT%H:%M:%SZ') - timedelta( hours = 5 )).strftime( '%Y-%m-%d,
      %H:%M')) }}"

condition: []

action:
  - service: notify.mobiles
    data:
      message: "{{state_attr('sensor.bin_collection', 'Reminder') }}"
      data:
        ttl: 0
        priority: high
