<<<<<<< HEAD
bathroom:
  # Binary Sensors
  #----------------------------------#
  binary_sensor:
    # Bayesian
    #----------------------------------#
    - platform: bayesian
      name: Bathroom Occupied
      prior: 0.11
      device_class: occupancy
      probability_threshold: 0.7
      observations:

        - platform: "state"
          entity_id: binary_sensor.bathroom_door_contact
          prob_given_true: 0.0056548
          prob_given_false: 0.0000373
          to_state: "off"

        - platform: "state"
          entity_id: binary_sensor.bathroom_motion
          prob_given_true: 0.3084673
          prob_given_false: 0.0014161
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.bathroom_motion_1_occupancy
          prob_given_true: 0.2988542
          prob_given_false: 0.0013911
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.bathroom_motion_2_occupancy
          prob_given_true: 0.2862158
          prob_given_false: 0.0013562
          to_state: "on"

        - platform: "state"
          entity_id: climate.bathroom_radiator
          prob_given_true: 0.0056548
          prob_given_false: 0.0000373
          to_state: "on"

        - platform: "state"
          entity_id: input_boolean.bathroom_schedule
          prob_given_true: 0.2792857
          prob_given_false: 0.0253888
          to_state: "on"

        - platform: "state"
          entity_id: input_boolean.shower_occupied
          prob_given_true: 0.3477679
          prob_given_false: 0.0015058
          to_state: "on"

    - platform: trend
      sensors:
        bathroom_humidity_falling_trend:
          friendly_name: Bathroom Humidity Falling Trend
          entity_id: sensor.bathroom_humidity_change
          sample_duration: 600
          max_samples: 10
          min_gradient: -0.033333333
          device_class: moisture

  # Variable Sensors
  #----------------------------------#

  sensor:
    - platform: average
      name: Bathroom Average Humidity
      unique_id: bathroom_average_humidity
      duration:
        days: 30
      entities:
        - sensor.bathroom_humidity

  # Template Sensors
  #----------------------------------#
  template:
    # Template Binary Sensors
    #----------------------------------#
    binary_sensor:
      # Bright Sensors
      #----------------------------------#
      - unique_id: bathroom_bright
        name: "Bathroom Bright"
        device_class: light
        attributes:
          current_illuminance: "{{ (states('sensor.bathroom_illuminance') | float(0)) }}"
          light_state: "{{ states('light.bathroom') }}"
          sun: "{{ states('sun.sun') }}"
        state: |
          {% if states('sensor.bathroom_illuminance') | int(0) > (states('input_number.bathroom_illuminance_level') | int(0) * 1.3) and is_state('light.bathroom', 'off') %}
            True
          {% elif states('sensor.bathroom_illuminance') | int(0) > (states('input_number.bathroom_illuminance_level') | int(0) * 3) %}
            True
          {% elif ((states('input_number.bathroom_illuminance_level') | int(0) < states('sensor.bathroom_illuminance') | int(0) < (states('input_number.bathroom_illuminance_level') | int(0) * 1.3 ))) and (as_timestamp(now())-as_timestamp(states.binary_sensor.bathroom_bright.last_changed) < 300) %}
            {{ states('binary_sensor.bathroom_bright') }}
          {% elif states('sensor.bathroom_illuminance') | int(0) < states('input_number.bathroom_illuminance_level') | int(0) %}
            False
          {% else %}
            False
          {% endif %}

      # Humid Sensors
      #----------------------------------#
      - unique_id: bathroom_humid
        name: "Bathroom Humid"
        device_class: moisture
        state: "{{states('sensor.bathroom_humidity') | float(51.0) > (states('sensor.bathroom_average_humidity') | float(50.0) * 1.3)}}"

    # Template Variable Sensors
    #----------------------------------#
    sensor:
      # Probabilities
      #----------------------------------#
      - unique_id: bathroom_occupied_probability
        name: Bathroom Occupied Probability
        state_class: measurement
        unit_of_measurement: "%"
        state: "{{ (state_attr('binary_sensor.bathroom_occupied','probability')*100 | int(0) ) | round(0) }}"
      - unique_id: bathroom_illuminance
        name: Bathroom Illuminance
        icon: mdi:brightness-5
        state_class: measurement
        unit_of_measurement: "lx"
        state: "{{ states('sensor.bathroom_illuminance') | float(1) }}"
  # Media Players
  #----------------------------------#
  media_player:

  # Notification Platforms
  #----------------------------------#
  notify:

  # Shell Commands
  #----------------------------------#
  shell_command:

  # Switches
  #----------------------------------#
  switch:

  # Cameras
  #----------------------------------#
  camera:
=======
bathroom:
  # Binary Sensors
  binary_sensor:
    - platform: bayesian
      name: Area - Bathroom Occupied
      prior: 0.0810
      device_class: occupancy
      probability_threshold: 0.70
      observations:
        - platform: "state"
          entity_id: "binary_sensor.area_bathroom_humidity_trend"
          prob_given_true: 0.2346
          prob_given_false: 0.0062
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.area_bathroom_temperature_trend"
          prob_given_true: 0.2346
          prob_given_false: 0.0093
          to_state: "on"
        - platform: "state"
          entity_id: binary_sensor.area_bathroom_humid
          prob_given_true: 0.3086
          prob_given_false: 0.0027
          to_state: "on"
        - platform: "state"
          entity_id: "group.area_bathroom_motion"
          prob_given_true: 0.8272
          prob_given_false: 0.0109
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.area_bathroom_bright"
          prob_given_true: 1.2048
          prob_given_false: 0.2853
          to_state: "on"
        - platform: "state"
          entity_id: "input_boolean.bathroom_schedule"
          prob_given_true: 2.0247
          prob_given_false: 0.1428
          to_state: "on"
    ####################################
    # Trend Binary Sensors
    ####################################
    - platform: trend
      sensors:
        # Humidity
        area_bathroom_humidity_trend:
          friendly_name: Area - Bathroom Humidity Trend
          entity_id: sensor.area_bathroom_humidity
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.011
          device_class: moisture
        # Temperature
        area_bathroom_temperature_trend:
          friendly_name: Area - Bathroom Temperature Trend
          entity_id: sensor.area_bathroom_temperature
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.0017
          device_class: heat
  # Sensors
  sensor:
    - platform: min_max
      name: Area - Bathroom Temperature
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.bathroom_tmp_02_temperature
        - sensor.bathroom_rad_01_temperature
    - platform: min_max
      name: Area - Bathroom Humidity
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.bathroom_tmp_02_humidity
    - platform: min_max
      name: Area - Bathroom Illuminance
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.bathroom_lux_02_illuminance_lux

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:
    area_bathroom_motion:
      name: Area - Bathroom Motion
      icon: mdi:motion-sensor
      entities:
        - binary_sensor.bathroom_mot_05_occupancy
        - binary_sensor.bathroom_mot_10_occupancy
  # Climate
  climate:
    - platform: climate_group
      name: Area - Bathroom Climate
      temperature_unit: C
      entities:
        - climate.bathroom_rad_01
        - climate.stairs_tst_01

  # Media Player
  media_player:

  # Notify
  notify:

  # Shell Command
  shell_command:

  # Switches
  switch:
>>>>>>> fcf4702d6d9777c62f997420e234fb70032d0604
