bathroom:
  # Binary Sensors
  binary_sensor:
    - platform: bayesian
      name: Area - Bathroom Occupied
      prior: 0.0810
      device_class: occupancy
      probability_threshold: 0.70
      observations:
        - platform: "state"
          entity_id: "binary_sensor.area_bathroom_humidity_trend"
          prob_given_true: 0.2346
          prob_given_false: 0.0062
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.area_bathroom_temperature_trend"
          prob_given_true: 0.2346
          prob_given_false: 0.0093
          to_state: "on"
        - platform: "state"
          entity_id: binary_sensor.area_bathroom_humid
          prob_given_true: 0.3086
          prob_given_false: 0.0027
          to_state: "on"
        - platform: "state"
          entity_id: "group.area_bathroom_motion"
          prob_given_true: 0.8272
          prob_given_false: 0.0109
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.area_bathroom_bright"
          prob_given_true: 1.2048
          prob_given_false: 0.2853
          to_state: "on"
        - platform: "state"
          entity_id: "input_boolean.bathroom_schedule"
          prob_given_true: 2.0247
          prob_given_false: 0.1428
          to_state: "on"
    ####################################
    # Trend Binary Sensors
    ####################################
    - platform: trend
      sensors:
        # Humidity
        area_bathroom_humidity_trend:
          friendly_name: Area - Bathroom Humidity Trend
          entity_id: sensor.area_bathroom_humidity
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.011
          device_class: moisture
        # Temperature
        area_bathroom_temperature_trend:
          friendly_name: Area - Bathroom Temperature Trend
          entity_id: sensor.area_bathroom_temperature
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.0017
          device_class: heat
  # Sensors
  sensor:
    - platform: min_max
      name: Area - Bathroom Temperature
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.bathroom_tmp_02_temperature
        - sensor.bathroom_rad_01_temperature
    - platform: min_max
      name: Area - Bathroom Humidity
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.bathroom_tmp_02_humidity
    - platform: min_max
      name: Area - Bathroom Illuminance
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.bathroom_lux_02_illuminance_lux

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:
    area_bathroom_motion:
      name: Area - Bathroom Motion
      icon: mdi:motion-sensor
      entities:
        - binary_sensor.bathroom_mot_05_occupancy
        - binary_sensor.bathroom_mot_10_occupancy
  # Climate
  climate:
    - platform: climate_group
      name: Area - Bathroom Climate
      temperature_unit: C
      entities:
        - climate.bathroom_rad_01
        - climate.stairs_tst_01

  # Media Player
  media_player:

  # Notify
  notify:

  # Shell Command
  shell_command:

  # Switches
  switch:
