bathroom:
  # Binary Sensors
  #----------------------------------#
  binary_sensor:
    # Bayesian
    #----------------------------------#
    - platform: bayesian
      name: Bathroom Occupied
      prior: 0.11
      device_class: occupancy
      probability_threshold: 0.7
      observations:

        - platform: "state"
          entity_id: binary_sensor.bathroom_door_contact
          prob_given_true: 0.0056548
          prob_given_false: 0.0000373
          to_state: "off"

        - platform: "state"
          entity_id: binary_sensor.bathroom_motion
          prob_given_true: 0.3084673
          prob_given_false: 0.0014161
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.bathroom_motion_1_occupancy
          prob_given_true: 0.2988542
          prob_given_false: 0.0013911
          to_state: "on"

        - platform: "state"
          entity_id: binary_sensor.bathroom_motion_2_occupancy
          prob_given_true: 0.2862158
          prob_given_false: 0.0013562
          to_state: "on"

        - platform: "state"
          entity_id: climate.bathroom_radiator
          prob_given_true: 0.0056548
          prob_given_false: 0.0000373
          to_state: "on"

        - platform: "state"
          entity_id: input_boolean.bathroom_schedule
          prob_given_true: 0.2792857
          prob_given_false: 0.0253888
          to_state: "on"

        - platform: "state"
          entity_id: input_boolean.shower_occupied
          prob_given_true: 0.3477679
          prob_given_false: 0.0015058
          to_state: "on"

    - platform: trend
      sensors:
        bathroom_humidity_falling_trend:
          friendly_name: Bathroom Humidity Falling Trend
          entity_id: sensor.bathroom_humidity_change
          sample_duration: 600
          max_samples: 10
          min_gradient: -0.033333333
          device_class: moisture

  # Variable Sensors
  #----------------------------------#

  sensor:

  # Template Sensors
  #----------------------------------#
  template:
    # Template Binary Sensors
    #----------------------------------#
    binary_sensor:
      # Bright Sensors
      #----------------------------------#
      - unique_id: bathroom_bright
        name: "Bathroom Bright"
        device_class: light
        state: |
          {% set lux = states('sensor.bathroom_illuminance') %}
          {% set threshold = states('input_number.bathroom_illuminance_level') %}
          {% set selfState = states('binary_sensor.bathroom_bright') %}
          {% set lightState = states('light.bathroom') %}
          {% set selfLastChanged = states.binary_sensor.bathroom_bright.last_changed %}
          {% if threshold | int(0) == 0 %}
            False
          {% elif lux | int(0) > (threshold | int(0) * 1.3) and lightState == 'off' %}
            True
          {% elif lux | int(0) > (threshold | int(0) * 3) %}
            True
          {% elif ((threshold | int(0) < lux | int(0) < (threshold | int(0) * 1.3 ))) and (as_timestamp(now())-as_timestamp(selfLastChanged) < 300) %}
            {{ selfState }}
          {% elif lux | int(0) < threshold | int(0) %}
            False
          {% else %}
            False
          {% endif %}


      # Humid Sensors
      #----------------------------------#
      - unique_id: bathroom_humid
        name: "Bathroom Humid"
        device_class: moisture
        state: "{{states('sensor.bathroom_humidity') | float(51.0) > (states('sensor.bathroom_average_humidity') | float(50.0) * 1.3)}}"

    # Template Variable Sensors
    #----------------------------------#
    sensor:
      # Probabilities
      #----------------------------------#
      - unique_id: bathroom_occupied_probability
        name: Bathroom Occupied Probability
        state_class: measurement
        unit_of_measurement: "%"
        state: "{{ (state_attr('binary_sensor.bathroom_occupied','probability')*100 | int(0) ) | round(0) }}"
  # Media Players
  #----------------------------------#
  media_player:

  # Notification Platforms
  #----------------------------------#
  notify:

  # Shell Commands
  #----------------------------------#
  shell_command:

  # Switches
  #----------------------------------#
  switch:

  # Cameras
  #----------------------------------#
  camera:
