hall:
  # Binary Sensors
  binary_sensor:
    - platform: bayesian
      name: Area - Hall Occupied
      prior: 0.02
      device_class: occupancy
      probability_threshold: 0.8
      observations:
        - platform: "state"
          entity_id: "group.area_hall_motion"
          prob_given_true: 0.96
          prob_given_false: 0.004
          to_state: "on"
        - platform: "state"
          entity_id: "binary_sensor.zone_hall_person_motion"
          prob_given_true: 0.9600
          prob_given_false: 0.0010
          to_state: "on"
    ####################################
    # Trend Binary Sensors
    ####################################
    - platform: trend
      sensors:
        # Humidity
        area_hall_humidity_trend:
          friendly_name: Area - Hall Humidity Trend
          entity_id: sensor.area_hall_humidity
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.011
          device_class: moisture
        # Temperature
        area_hall_temperature_trend:
          friendly_name: Area - Hall Temperature Trend
          entity_id: sensor.area_hall_temperature
          sample_duration: 1200
          max_samples: 6
          min_gradient: 0.0017
          device_class: heat
  # Sensors
  sensor:
    - platform: min_max
      name: Area - Hall Temperature
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.tst_01_temperature
    - platform: min_max
      name: Area - Hall Illuminance
      type: mean
      round_digits: 1
      entity_ids:
        - sensor.hall_lux_07_illuminance_lux

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:
    area_hall_motion:
      name: Area - Hall Motion
      icon: mdi:motion-sensor
      entities:
        - binary_sensor.hall_mot_09_occupancy
  # Climate
  climate:
    - platform: climate_group
      name: Area - Hall Climate
      temperature_unit: C
      entities:
        - climate.stairs_tst_01

  # Media Player
  media_player:

  # Notify
  notify:

  # Shell Command
  shell_command:
    hall_camera_turn_off: !secret hallcam_turn_off
    hall_camera_turn_on: !secret hallcam_turn_on
    hall_camera_bedroom: !secret hallcam_bedroom
    hall_camera_study: !secret hallcam_study
    hall_camera_landing: !secret hallcam_landing
    hall_camera_stairs: !secret hallcam_stairs
  # Switches
  switch:
    - platform: command_line
      switches:
        hall_camera_ir:
          friendly_name: Lounge Camera Night Mode
          command_on: !secret hallcam_ir_on
          command_off: !secret hallcam_ir_off
          command_state: !secret hallcam_ir_state
          value_template: '{{ value == "1" }}'
        hall_camera_motion:
          friendly_name: Lounge Camera Motion Detection
          command_on: !secret hallcam_motion_on
          command_off: !secret hallcam_motion_off
          command_state: !secret hallcam_motion_state
          value_template: '{{ value == "1" }}'
