hall:
  template:
    - binary_sensor:
        - name: Hall Occupancy
          unique_id: hall_occupancy
          device_class: occupancy
          state: |-
            {% set scores = namespace(total=0) %}
            {% if is_state('binary_sensor.hall_motion', 'on') %}  {% set scores.total = scores.total + 3 %}{% endif %}
            {% if is_state('binary_sensor.hall_door_contact', 'off') %}  {% set scores.total = scores.total + 1 %}{% endif %}
            {% if is_state('input_boolean.hall_occupied_override', 'on') %}  {% set scores.total = scores.total + 5 %}{% endif %}
            {{ scores.total >= 3 }}
          attributes:
            confidence_score: |-
              {% set scores = namespace(total=0) %}
              {% if is_state('binary_sensor.hall_motion', 'on') %}  {% set scores.total = scores.total + 3 %}{% endif %}
              {% if is_state('binary_sensor.hall_door_contact', 'off') %}  {% set scores.total = scores.total + 1 %}{% endif %}
              {% if is_state('input_boolean.hall_occupied_override', 'on') %}  {% set scores.total = scores.total + 5 %}{% endif %}
              {{ scores.total }}
            active_triggers: |-
              {% set triggers = [] %}
              {% if is_state('binary_sensor.hall_motion', 'on') %}  {% set triggers = triggers + ['Motion Detected'] %}{% endif %}
              {% if is_state('binary_sensor.hall_door_contact', 'off') %}  {% set triggers = triggers + ['Door Closed'] %}{% endif %}
              {% if is_state('input_boolean.hall_occupied_override', 'on') %}  {% set triggers = triggers + ['Manual Override'] %}{% endif %}
              {{ triggers|join(', ') }}
  input_number:
    hall_light_brightness:
      name: Hall Light Brightness
      min: 0.0
      max: 100.0
      step: 5.0
      unit_of_measurement: "%"
      icon: mdi:brightness-6
      initial: 100.0
    hall_light_transition:
      name: Hall Light Transition Time
      min: 0.0
      max: 10.0
      step: 0.5
      unit_of_measurement: s
      icon: mdi:transition
      initial: 2.0
    hall_humidity_threshold:
      name: Hall Humidity Threshold
      min: 30.0
      max: 80.0
      step: 1.0
      unit_of_measurement: "%"
      icon: mdi:water-percent
      initial: 60.0
  input_boolean:
    hall_light_color_mode:
      name: Hall Light Color Mode
      icon: mdi:palette
    hall_occupied_override:
      name: Hall Manual Occupancy Override
      icon: mdi:account-check
    hall_sleep_mode:
      name: Hall Sleep Mode
      icon: mdi:power-sleep
    hall_automations:
      name: Hall Automations
      icon: mdi:robot
