alias: Room - Lounge - Lights
id: 027c7b02-12e8-4d99-8154-05b903a2e8dc
description: ""
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.area_lounge_occupied
      - binary_sensor.area_lounge_bright
      - input_boolean.area_lounge_automations
      - binary_sensor.people_home

condition:
  - condition: state
    entity_id: input_boolean.area_lounge_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            state: "on"
            entity_id: binary_sensor.area_lounge_occupied
          - condition: state
            state: "off"
            entity_id: binary_sensor.area_lounge_bright
          - condition: state
            state: "on"
            entity_id: binary_sensor.people_home
        sequence:
          - service: light.turn_on
            target:
              area_id: lounge
            data:
              transition: 3
              color_temp: "{{ state_attr('switch.adaptive_lighting_adaptive_lights', 'color_temp_mired') }}"
              brightness_pct: "{{ state_attr('switch.adaptive_lighting_adaptive_lights', 'brightness_pct') | int }}"
    default:
      - service: light.turn_off
        target:
          area_id: lounge
        data:
          transition: 3
