alias: Room - Lounge - Lights
id: 027c7b02-12e8-4d99-8154-05b903a2e8dc
description: ""
mode: queued

trigger:
  - platform: homeassistant
    event: start
  - platform: event
    event_type: automation_reloaded
  - platform: state
    entity_id:
      - binary_sensor.area_lounge_occupied
      - binary_sensor.area_lounge_bright
      - input_boolean.area_lounge_automations

condition:
  - condition: state
    entity_id: input_boolean.area_lounge_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.area_lounge_bright
            state: "off"
          - condition: not
            conditions:
              - condition: state
                entity_id: media_player.lounge_tv
                state: "off"
              - condition: state
                entity_id: media_player.lounge_tv
                state: "unknown"
              - condition: state
                entity_id: media_player.lounge_tv
                state: "unavailable"
          - condition: state
            entity_id: binary_sensor.area_lounge_occupied
            state: "on"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 30
            target:
              entity_id: light.lounge_lights
      - conditions:
          - condition: state
            entity_id: binary_sensor.area_lounge_bright
            state: "off"
          - condition: state
            entity_id: binary_sensor.area_lounge_occupied
            state: "on"
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
            target:
              entity_id: light.lounge_lights
    default:
      - service: light.turn_off
        target:
          area_id: lounge
