alias: Room - Lounge - Lights
id: 027c7b02-12e8-4d99-8154-05b903a2e8dc
description: ""
mode: queued

trigger:
  - platform: state
    entity_id: binary_sensor.lounge_trisensor_motion
  - entity_id: media_player.lounge_tv
    platform: state
  - entity_id: binary_sensor.lounge_bright
    platform: state

condition:
  - condition: state
    entity_id: input_boolean.lounge_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.lounge_trisensor_motion
            state: "on"
          - condition: state
            entity_id: media_player.lounge_tv
            state: "off"
          - condition: state
            entity_id: binary_sensor.lounge_bright
            state: "off"
        sequence:
          - data:
              brightness_pct: 100
            service: light.turn_on
            target:
              entity_id: light.lounge_lights
      - conditions:
          - condition: not
            conditions:
              - condition: state
                entity_id: media_player.lounge_tv
                state: "off"
          - condition: state
            entity_id: binary_sensor.lounge_bright
            state: "off"
        sequence:
          - data:
              brightness_pct: 30
            service: light.turn_on
            target:
              entity_id: light.lounge_lights
      - conditions:
          - condition: state
            entity_id: binary_sensor.lounge_bright
            state: "on"
        sequence:
          - service: light.turn_off
            target:
              entity_id: light.lounge_lights
    default:
      - service: light.turn_off
        target:
          entity_id: light.lounge_lights
