alias: Room - Study - Lights
id: 436d5a1c-3313-46f5-91af-c7964998b2a0
description: ""
mode: queued

trigger:
  - platform: state
    entity_id:
      - binary_sensor.area_study_occupied
      - sun.sun

condition:
  - condition: state
    entity_id: input_boolean.area_study_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.area_study_occupied
            state: "on"
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.area_study_bright
                state: "off"
              - condition: state
                entity_id: sun.sun
                state: below_horizon
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
            target:
              entity_id: light.study_lights
    default:
      - condition: and
        conditions:
          - condition: state
            entity_id: binary_sensor.area_study_occupied
            state: "off"
          - condition: or
            conditions:
              - condition: state
                entity_id: binary_sensor.starrunner_active
                state: "off"
              - condition: state
                entity_id: binary_sensor.starrunner_active
                state: unavailable
      - service: light.turn_off
        target:
          area_id: study
