alias: Room - Bathroom - Lights
id: c87f8826-584c-4459-ac6e-8d3615702dad
description: ""
mode: queued

trigger:
  - platform: state
    entity_id:
      - binary_sensor.area_bathroom_occupied

condition:
  - condition: state
    entity_id: input_boolean.area_bathroom_automations
    state: "on"

action:
  - choose:
      - conditions:
          - condition: state
            state: "on"
            entity_id: binary_sensor.area_bathroom_occupied
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
            target:
              area_id: bathroom
    default:
      - condition: state
        entity_id: binary_sensor.area_bathroom_occupied
        state: "off"
      - service: light.turn_off
        target:
          area_id: bathroom
