substitutions:
  name: study-aq
packages:
  LoopOn.AirSense: github://LoopOnCode/AirSense/esphome/loopon_airsense.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
api:
  encryption:
    key: /d8olq95lJs7orDn842p2LZTzUbb4iyLP3SdtsNDy0k=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
