substitutions:
  name: bedroom-speaker-6b49cc
  friendly_name: Bedroom Speaker
packages:
  raspiaudio.muse-luxe-voice-assistant: github://esphome/firmware/voice-assistant/raspiaudio-muse-luxe.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: KzDxXbhgZZfXIdL2jdi2nZVuylS2z83K6otkfCyKbAY=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
