<<<<<<< HEAD
wardrobe:
  # Binary Sensors
  #----------------------------------#
  binary_sensor:
    # Bayesian
    #----------------------------------#
    - platform: bayesian
      name: Wardrobe Occupied
      prior: 0.08
      device_class: occupancy
      probability_threshold: 0.7
      observations:

        - platform: "state"
          entity_id: binary_sensor.wardrobe_motion
          prob_given_true: 0.2634554
          prob_given_false: 0.0008475
          to_state: "on"

  # Variable Sensors
  #----------------------------------#
  sensor:

  # Template Sensors
  #----------------------------------#
  template:
    # Template Binary Sensors
    #----------------------------------#
    binary_sensor:
      # Bright Sensors
      #----------------------------------#

    # Template Variable Sensors
    #----------------------------------#
    sensor:
  # Thermostats
  #----------------------------------#
  climate:

  # Media Players
  #----------------------------------#
  media_player:

  # Notification Platforms
  #----------------------------------#
  notify:

  # Shell Commands
  #----------------------------------#
  shell_command:

  # Switches
  #----------------------------------#
  switch:
=======
wardrobe:
  # Binary Sensors
  binary_sensor:
    - platform: bayesian
      name: Area - Wardrobe Occupied
      prior: 0.02
      device_class: occupancy
      probability_threshold: 0.6
      observations:
        - platform: "state"
          entity_id: "group.area_wardrobe_motion"
          prob_given_true: 0.48
          prob_given_false: 0.0043
          to_state: "on"
  # Sensors
  sensor:

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:
    area_wardrobe_motion:
      name: Area - Wardrobe Motion
      icon: mdi:motion-sensor
      entities:
        - binary_sensor.wardrobe_mot_11_occupancy
  # Climate
  climate:

  # Media Player
  media_player:

  # Notify
  notify:

  # Shell Command
  shell_command:

  # Switches
  switch:
>>>>>>> fcf4702d6d9777c62f997420e234fb70032d0604
