wardrobe:
  # Binary Sensors
  binary_sensor:
    - platform: bayesian
      name: Area - Wardrobe Occupied
      prior: 0.02
      device_class: occupancy
      probability_threshold: 0.6
      observations:
        - platform: "state"
          entity_id: "group.area_wardrobe_motion"
          prob_given_true: 0.48
          prob_given_false: 0.0043
          to_state: "on"
  # Sensors
  sensor:

  # Template
  template:
    # Binary Sensors
    binary_sensor:

    # Sensors
    sensor:

  # Groups
  group:
    area_wardrobe_motion:
      name: Area - Wardrobe Motion
      icon: mdi:motion-sensor
      entities:
        - binary_sensor.wardrobe_mot_11_occupancy
  # Climate
  climate:

  # Media Player
  media_player:

  # Notify
  notify:

  # Shell Command
  shell_command:

  # Switches
  switch:
