substitutions:
  area: Bedroom
  arealower: bedroom

esphome:
  name: ${arealower}-bed-presence
  name_add_mac_suffix: false

esp32:
  board: az-delivery-devkit-v4
  framework:
    type: arduino

ota:
logger:
api:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

button:
  - platform: restart
    name: ${area} Bed Presence Restart
    id: ${arealower}_bed_presence_restart
    entity_category: config

sensor:
  - platform: homeassistant
    id: homeassistant_bed_left_average_voltage
    entity_id: sensor.bed_left_average_voltage
  - platform: homeassistant
    id: homeassistant_bed_right_average_voltage
    entity_id: sensor.bed_right_average_voltage
  - platform: adc
    pin: GPIO34
    attenuation: 11db
    name: ${area} Bed Presence Left Voltage
    id: ${arealower}_bed_presence_left_voltage
    entity_category: diagnostic
    icon: mdi:bed
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 5 # The number of most recent readings used to calculate the average
          send_every: 1 # The filter waits until it has received this many readings before sending a value.
      - or:
          - throttle: 60s # This filter ensures that a reading is sent at least every 60 seconds
          - delta: 0.01 # This filter ensures that a reading is sent if it changes by more than 0.01
  - platform: adc
    pin: GPIO35
    attenuation: 11db
    name: ${area} Bed Presence Right Voltage
    id: ${arealower}_bed_presence_right_voltage
    entity_category: diagnostic
    icon: mdi:bed
    update_interval: 1s
    filters:
      - sliding_window_moving_average:
          window_size: 5 # The number of most recent readings used to calculate the average
          send_every: 1 # The filter waits until it has received this many readings before sending a value.
      - or:
          - throttle: 60s # This filter ensures that a reading is sent at least every 60 seconds
          - delta: 0.01 # This filter ensures that a reading is sent if it changes by more than 0.01

number:
  - platform: template
    name: ${area} Bed Presence Left Threshold
    id: ${arealower}_bed_presence_left_threshold
    optimistic: true
    min_value: 0
    max_value: 3.3
    step: 0.01
    restore_value: true
    initial_value: 1.0
    mode: box
    unit_of_measurement: V
    entity_category: config
  - platform: template
    name: ${area} Bed Presence Right Threshold
    id: ${arealower}_bed_presence_right_threshold
    optimistic: true
    min_value: 0
    max_value: 3.3
    step: 0.01
    restore_value: true
    initial_value: 1.0
    mode: box
    unit_of_measurement: V
    entity_category: config

binary_sensor:
  - platform: template
    name: ${area} Bed Presence Left Occupied
    id: ${arealower}_bed_presence_left_occupied
    device_class: occupancy
    entity_category: diagnostic
    lambda: |-
      if (id(${arealower}_bed_presence_left_voltage).state > id(homeassistant_bed_left_average_voltage).state) {
        return true;
      } else {
        return false;
      }
  - platform: template
    name: ${area} Bed Presence Right Occupied
    id: ${arealower}_bed_presence_right_occupied
    device_class: occupancy
    entity_category: diagnostic
    lambda: |-
      if (id(${arealower}_bed_presence_right_voltage).state > id(homeassistant_bed_right_average_voltage).state) {
        return true;
      } else {
        return false;
      }
