substitutions:
  name: home-assistant-voice-0941d1
  friendly_name: Home Assistant Voice 0941d1
packages:
  Nabu Casa.Home Assistant Voice PE: github://esphome/home-assistant-voice-pe/home-assistant-voice.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 6bweQfukggoCaGSdvTsJIaEv0kNB0g/dCD4Hk/Jv8s8=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
