system:
  #browser_mod:

  battery_notes:

  csv_exporter:

  python_script:

  readme:

  group:
    all_automations:
      name: All Automations
      icon: mdi:robot
      all: true
      entities:
        - input_boolean.bathroom_automations
        - input_boolean.bedroom_automations
        - input_boolean.entrance_automations
        - input_boolean.hall_automations
        - input_boolean.home_automations
        - input_boolean.kitchen_automations
        - input_boolean.lounge_automations
        - input_boolean.study_automations
        - input_boolean.toilet_automations

  notify:
    - name: Mobiles
      platform: group
      services:
        - service: mobile_app_seb_phone
        - service: mobile_app_laura_phone
    - name: Seb's Devices
      platform: group
      services:
        - service: mobile_app_seb_phone
        - service: mobile_app_seb_watch
    - platform: file
      name: entity_log
      filename: /config/www/entity_log.txt
      timestamp: false

  sensor:
    - platform: email
      email: !secret seb_email
      password: !secret seb_email_password
      imap_server: outlook.office365.com
      imap_port: 993
    - platform: time_date
      display_options:
        - "date"
        - "date_time"
        - "date_time_iso"

  tts:
    platform: google_translate
    language: "en"
    cache: true
    cache_dir: /tmp/ttsr fast play
    time_memory: 300
